// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: anovel/genai/v0/generation_submit.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerationSubmitRequest carries a new generation. The server mints the id and the timestamps.
type GenerationSubmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OwnerID is the user this acts for, formatted as a UUID. Supplied by the calling service, which
	// verified it against its own credential — this service does not authenticate.
	OwnerId string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Purpose labels what the spend is attributed to. Required, and otherwise opaque: the vocabulary
	// belongs to the caller.
	Purpose string `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// IdempotencyKey deduplicates repeat submissions within one owner. Required — an unkeyed
	// submission of a priced call is a bug rather than a default worth tolerating. A value reused
	// with a different request is a conflict, not a replay.
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// Request is the provider payload, as JSON bytes, forwarded verbatim. The caller owns every
	// parameter in it; this service merges in only what crash-safety requires. At most 3,688,000
	// bytes.
	Request []byte `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty"`
	// MaxAttempts caps the runs this generation gets. Zero means one, the right floor for a priced
	// call.
	MaxAttempts   int32 `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationSubmitRequest) Reset() {
	*x = GenerationSubmitRequest{}
	mi := &file_anovel_genai_v0_generation_submit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationSubmitRequest) ProtoMessage() {}

func (x *GenerationSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_submit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationSubmitRequest.ProtoReflect.Descriptor instead.
func (*GenerationSubmitRequest) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_submit_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationSubmitRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GenerationSubmitRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *GenerationSubmitRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *GenerationSubmitRequest) GetRequest() []byte {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *GenerationSubmitRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

// GenerationSubmitResponse returns the recorded generation and whether this call created it.
type GenerationSubmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generation is the recorded generation — the newly created one, or the existing one on a replay.
	Generation *Generation `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// Created is false when an existing generation was returned under the same idempotency key, so a
	// caller retrying a request attaches to work already in flight instead of paying for a second one.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationSubmitResponse) Reset() {
	*x = GenerationSubmitResponse{}
	mi := &file_anovel_genai_v0_generation_submit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationSubmitResponse) ProtoMessage() {}

func (x *GenerationSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_submit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationSubmitResponse.ProtoReflect.Descriptor instead.
func (*GenerationSubmitResponse) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_submit_proto_rawDescGZIP(), []int{1}
}

func (x *GenerationSubmitResponse) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *GenerationSubmitResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_anovel_genai_v0_generation_submit_proto protoreflect.FileDescriptor

const file_anovel_genai_v0_generation_submit_proto_rawDesc = "" +
	"\n" +
	"'anovel/genai/v0/generation_submit.proto\x12\x0fanovel.genai.v0\x1a anovel/genai/v0/generation.proto\"\xb4\x01\n" +
	"\x17GenerationSubmitRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\arequest\x18\x04 \x01(\fR\arequest\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\x05R\vmaxAttempts\"q\n" +
	"\x18GenerationSubmitResponse\x12;\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x1b.anovel.genai.v0.GenerationR\n" +
	"generation\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated2\x82\x01\n" +
	"\x17GenerationSubmitService\x12g\n" +
	"\x10GenerationSubmit\x12(.anovel.genai.v0.GenerationSubmitRequest\x1a).anovel.genai.v0.GenerationSubmitResponseB\xd7\x01\n" +
	"\x13com.anovel.genai.v0B\x15GenerationSubmitProtoP\x01ZKgithub.com/a-novel/service-genai/internal/handlers/protogen/anovel/genai/v0\xa2\x02\x03AGV\xaa\x02\x0fAnovel.Genai.V0\xca\x02\x0fAnovel\\Genai\\V0\xe2\x02\x1bAnovel\\Genai\\V0\\GPBMetadata\xea\x02\x11Anovel::Genai::V0b\x06proto3"

var (
	file_anovel_genai_v0_generation_submit_proto_rawDescOnce sync.Once
	file_anovel_genai_v0_generation_submit_proto_rawDescData []byte
)

func file_anovel_genai_v0_generation_submit_proto_rawDescGZIP() []byte {
	file_anovel_genai_v0_generation_submit_proto_rawDescOnce.Do(func() {
		file_anovel_genai_v0_generation_submit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_submit_proto_rawDesc), len(file_anovel_genai_v0_generation_submit_proto_rawDesc)))
	})
	return file_anovel_genai_v0_generation_submit_proto_rawDescData
}

var file_anovel_genai_v0_generation_submit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anovel_genai_v0_generation_submit_proto_goTypes = []any{
	(*GenerationSubmitRequest)(nil),  // 0: anovel.genai.v0.GenerationSubmitRequest
	(*GenerationSubmitResponse)(nil), // 1: anovel.genai.v0.GenerationSubmitResponse
	(*Generation)(nil),               // 2: anovel.genai.v0.Generation
}
var file_anovel_genai_v0_generation_submit_proto_depIdxs = []int32{
	2, // 0: anovel.genai.v0.GenerationSubmitResponse.generation:type_name -> anovel.genai.v0.Generation
	0, // 1: anovel.genai.v0.GenerationSubmitService.GenerationSubmit:input_type -> anovel.genai.v0.GenerationSubmitRequest
	1, // 2: anovel.genai.v0.GenerationSubmitService.GenerationSubmit:output_type -> anovel.genai.v0.GenerationSubmitResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anovel_genai_v0_generation_submit_proto_init() }
func file_anovel_genai_v0_generation_submit_proto_init() {
	if File_anovel_genai_v0_generation_submit_proto != nil {
		return
	}
	file_anovel_genai_v0_generation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_submit_proto_rawDesc), len(file_anovel_genai_v0_generation_submit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anovel_genai_v0_generation_submit_proto_goTypes,
		DependencyIndexes: file_anovel_genai_v0_generation_submit_proto_depIdxs,
		MessageInfos:      file_anovel_genai_v0_generation_submit_proto_msgTypes,
	}.Build()
	File_anovel_genai_v0_generation_submit_proto = out.File
	file_anovel_genai_v0_generation_submit_proto_goTypes = nil
	file_anovel_genai_v0_generation_submit_proto_depIdxs = nil
}
