// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: anovel/genai/v0/generation_watch.proto

package v0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenerationWatchService_GenerationWatch_FullMethodName = "/anovel.genai.v0.GenerationWatchService/GenerationWatch"
)

// GenerationWatchServiceClient is the client API for GenerationWatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GenerationWatchService streams a generation's state to a caller waiting on its outcome.
//
// The stream is resumable by construction: a caller that reconnects calls it again, and the server
// answers from current state — the generation as it stands now, then each change until it is
// terminal. There is no cursor and no window in which a change can be missed, because the stream
// reads durable state rather than consuming events.
//
// A caller that wants a single answer uses GenerationGet instead; this is the latency lever for a
// caller that would otherwise poll.
type GenerationWatchServiceClient interface {
	GenerationWatch(ctx context.Context, in *GenerationWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerationWatchResponse], error)
}

type generationWatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerationWatchServiceClient(cc grpc.ClientConnInterface) GenerationWatchServiceClient {
	return &generationWatchServiceClient{cc}
}

func (c *generationWatchServiceClient) GenerationWatch(ctx context.Context, in *GenerationWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerationWatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GenerationWatchService_ServiceDesc.Streams[0], GenerationWatchService_GenerationWatch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerationWatchRequest, GenerationWatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GenerationWatchService_GenerationWatchClient = grpc.ServerStreamingClient[GenerationWatchResponse]

// GenerationWatchServiceServer is the server API for GenerationWatchService service.
// All implementations must embed UnimplementedGenerationWatchServiceServer
// for forward compatibility.
//
// GenerationWatchService streams a generation's state to a caller waiting on its outcome.
//
// The stream is resumable by construction: a caller that reconnects calls it again, and the server
// answers from current state — the generation as it stands now, then each change until it is
// terminal. There is no cursor and no window in which a change can be missed, because the stream
// reads durable state rather than consuming events.
//
// A caller that wants a single answer uses GenerationGet instead; this is the latency lever for a
// caller that would otherwise poll.
type GenerationWatchServiceServer interface {
	GenerationWatch(*GenerationWatchRequest, grpc.ServerStreamingServer[GenerationWatchResponse]) error
	mustEmbedUnimplementedGenerationWatchServiceServer()
}

// UnimplementedGenerationWatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerationWatchServiceServer struct{}

func (UnimplementedGenerationWatchServiceServer) GenerationWatch(*GenerationWatchRequest, grpc.ServerStreamingServer[GenerationWatchResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerationWatch not implemented")
}
func (UnimplementedGenerationWatchServiceServer) mustEmbedUnimplementedGenerationWatchServiceServer() {
}
func (UnimplementedGenerationWatchServiceServer) testEmbeddedByValue() {}

// UnsafeGenerationWatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerationWatchServiceServer will
// result in compilation errors.
type UnsafeGenerationWatchServiceServer interface {
	mustEmbedUnimplementedGenerationWatchServiceServer()
}

func RegisterGenerationWatchServiceServer(s grpc.ServiceRegistrar, srv GenerationWatchServiceServer) {
	// If the following call panics, it indicates UnimplementedGenerationWatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenerationWatchService_ServiceDesc, srv)
}

func _GenerationWatchService_GenerationWatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerationWatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GenerationWatchServiceServer).GenerationWatch(m, &grpc.GenericServerStream[GenerationWatchRequest, GenerationWatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GenerationWatchService_GenerationWatchServer = grpc.ServerStreamingServer[GenerationWatchResponse]

// GenerationWatchService_ServiceDesc is the grpc.ServiceDesc for GenerationWatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenerationWatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anovel.genai.v0.GenerationWatchService",
	HandlerType: (*GenerationWatchServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerationWatch",
			Handler:       _GenerationWatchService_GenerationWatch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "anovel/genai/v0/generation_watch.proto",
}
