// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: anovel/genai/v0/generation_cancel.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerationCancelRequest identifies the generation to stop and the owner it must belong to.
type GenerationCancelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the generation to stop, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// OwnerID scopes the request, formatted as a UUID.
	OwnerId       string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationCancelRequest) Reset() {
	*x = GenerationCancelRequest{}
	mi := &file_anovel_genai_v0_generation_cancel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationCancelRequest) ProtoMessage() {}

func (x *GenerationCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_cancel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationCancelRequest.ProtoReflect.Descriptor instead.
func (*GenerationCancelRequest) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_cancel_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationCancelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerationCancelRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// GenerationCancelResponse returns the generation with the request recorded. Its status is
// unchanged: the worker settles it once the provider operation has actually stopped.
type GenerationCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *Generation            `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationCancelResponse) Reset() {
	*x = GenerationCancelResponse{}
	mi := &file_anovel_genai_v0_generation_cancel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationCancelResponse) ProtoMessage() {}

func (x *GenerationCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_cancel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationCancelResponse.ProtoReflect.Descriptor instead.
func (*GenerationCancelResponse) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_cancel_proto_rawDescGZIP(), []int{1}
}

func (x *GenerationCancelResponse) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

var File_anovel_genai_v0_generation_cancel_proto protoreflect.FileDescriptor

const file_anovel_genai_v0_generation_cancel_proto_rawDesc = "" +
	"\n" +
	"'anovel/genai/v0/generation_cancel.proto\x12\x0fanovel.genai.v0\x1a anovel/genai/v0/generation.proto\"D\n" +
	"\x17GenerationCancelRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"W\n" +
	"\x18GenerationCancelResponse\x12;\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x1b.anovel.genai.v0.GenerationR\n" +
	"generation2\x82\x01\n" +
	"\x17GenerationCancelService\x12g\n" +
	"\x10GenerationCancel\x12(.anovel.genai.v0.GenerationCancelRequest\x1a).anovel.genai.v0.GenerationCancelResponseB\xd7\x01\n" +
	"\x13com.anovel.genai.v0B\x15GenerationCancelProtoP\x01ZKgithub.com/a-novel/service-genai/internal/handlers/protogen/anovel/genai/v0\xa2\x02\x03AGV\xaa\x02\x0fAnovel.Genai.V0\xca\x02\x0fAnovel\\Genai\\V0\xe2\x02\x1bAnovel\\Genai\\V0\\GPBMetadata\xea\x02\x11Anovel::Genai::V0b\x06proto3"

var (
	file_anovel_genai_v0_generation_cancel_proto_rawDescOnce sync.Once
	file_anovel_genai_v0_generation_cancel_proto_rawDescData []byte
)

func file_anovel_genai_v0_generation_cancel_proto_rawDescGZIP() []byte {
	file_anovel_genai_v0_generation_cancel_proto_rawDescOnce.Do(func() {
		file_anovel_genai_v0_generation_cancel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_cancel_proto_rawDesc), len(file_anovel_genai_v0_generation_cancel_proto_rawDesc)))
	})
	return file_anovel_genai_v0_generation_cancel_proto_rawDescData
}

var file_anovel_genai_v0_generation_cancel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anovel_genai_v0_generation_cancel_proto_goTypes = []any{
	(*GenerationCancelRequest)(nil),  // 0: anovel.genai.v0.GenerationCancelRequest
	(*GenerationCancelResponse)(nil), // 1: anovel.genai.v0.GenerationCancelResponse
	(*Generation)(nil),               // 2: anovel.genai.v0.Generation
}
var file_anovel_genai_v0_generation_cancel_proto_depIdxs = []int32{
	2, // 0: anovel.genai.v0.GenerationCancelResponse.generation:type_name -> anovel.genai.v0.Generation
	0, // 1: anovel.genai.v0.GenerationCancelService.GenerationCancel:input_type -> anovel.genai.v0.GenerationCancelRequest
	1, // 2: anovel.genai.v0.GenerationCancelService.GenerationCancel:output_type -> anovel.genai.v0.GenerationCancelResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anovel_genai_v0_generation_cancel_proto_init() }
func file_anovel_genai_v0_generation_cancel_proto_init() {
	if File_anovel_genai_v0_generation_cancel_proto != nil {
		return
	}
	file_anovel_genai_v0_generation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_cancel_proto_rawDesc), len(file_anovel_genai_v0_generation_cancel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anovel_genai_v0_generation_cancel_proto_goTypes,
		DependencyIndexes: file_anovel_genai_v0_generation_cancel_proto_depIdxs,
		MessageInfos:      file_anovel_genai_v0_generation_cancel_proto_msgTypes,
	}.Build()
	File_anovel_genai_v0_generation_cancel_proto = out.File
	file_anovel_genai_v0_generation_cancel_proto_goTypes = nil
	file_anovel_genai_v0_generation_cancel_proto_depIdxs = nil
}
