// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: anovel/genai/v0/generation_get.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerationGetRequest identifies the generation to read and the owner it must belong to.
type GenerationGetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the generation to read, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// OwnerID scopes the read, formatted as a UUID.
	OwnerId       string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationGetRequest) Reset() {
	*x = GenerationGetRequest{}
	mi := &file_anovel_genai_v0_generation_get_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationGetRequest) ProtoMessage() {}

func (x *GenerationGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_get_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationGetRequest.ProtoReflect.Descriptor instead.
func (*GenerationGetRequest) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_get_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerationGetRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// GenerationGetResponse returns the generation.
type GenerationGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *Generation            `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationGetResponse) Reset() {
	*x = GenerationGetResponse{}
	mi := &file_anovel_genai_v0_generation_get_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationGetResponse) ProtoMessage() {}

func (x *GenerationGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_get_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationGetResponse.ProtoReflect.Descriptor instead.
func (*GenerationGetResponse) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_get_proto_rawDescGZIP(), []int{1}
}

func (x *GenerationGetResponse) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

var File_anovel_genai_v0_generation_get_proto protoreflect.FileDescriptor

const file_anovel_genai_v0_generation_get_proto_rawDesc = "" +
	"\n" +
	"$anovel/genai/v0/generation_get.proto\x12\x0fanovel.genai.v0\x1a anovel/genai/v0/generation.proto\"A\n" +
	"\x14GenerationGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"T\n" +
	"\x15GenerationGetResponse\x12;\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x1b.anovel.genai.v0.GenerationR\n" +
	"generation2v\n" +
	"\x14GenerationGetService\x12^\n" +
	"\rGenerationGet\x12%.anovel.genai.v0.GenerationGetRequest\x1a&.anovel.genai.v0.GenerationGetResponseB\xd4\x01\n" +
	"\x13com.anovel.genai.v0B\x12GenerationGetProtoP\x01ZKgithub.com/a-novel/service-genai/internal/handlers/protogen/anovel/genai/v0\xa2\x02\x03AGV\xaa\x02\x0fAnovel.Genai.V0\xca\x02\x0fAnovel\\Genai\\V0\xe2\x02\x1bAnovel\\Genai\\V0\\GPBMetadata\xea\x02\x11Anovel::Genai::V0b\x06proto3"

var (
	file_anovel_genai_v0_generation_get_proto_rawDescOnce sync.Once
	file_anovel_genai_v0_generation_get_proto_rawDescData []byte
)

func file_anovel_genai_v0_generation_get_proto_rawDescGZIP() []byte {
	file_anovel_genai_v0_generation_get_proto_rawDescOnce.Do(func() {
		file_anovel_genai_v0_generation_get_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_get_proto_rawDesc), len(file_anovel_genai_v0_generation_get_proto_rawDesc)))
	})
	return file_anovel_genai_v0_generation_get_proto_rawDescData
}

var file_anovel_genai_v0_generation_get_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anovel_genai_v0_generation_get_proto_goTypes = []any{
	(*GenerationGetRequest)(nil),  // 0: anovel.genai.v0.GenerationGetRequest
	(*GenerationGetResponse)(nil), // 1: anovel.genai.v0.GenerationGetResponse
	(*Generation)(nil),            // 2: anovel.genai.v0.Generation
}
var file_anovel_genai_v0_generation_get_proto_depIdxs = []int32{
	2, // 0: anovel.genai.v0.GenerationGetResponse.generation:type_name -> anovel.genai.v0.Generation
	0, // 1: anovel.genai.v0.GenerationGetService.GenerationGet:input_type -> anovel.genai.v0.GenerationGetRequest
	1, // 2: anovel.genai.v0.GenerationGetService.GenerationGet:output_type -> anovel.genai.v0.GenerationGetResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anovel_genai_v0_generation_get_proto_init() }
func file_anovel_genai_v0_generation_get_proto_init() {
	if File_anovel_genai_v0_generation_get_proto != nil {
		return
	}
	file_anovel_genai_v0_generation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_get_proto_rawDesc), len(file_anovel_genai_v0_generation_get_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anovel_genai_v0_generation_get_proto_goTypes,
		DependencyIndexes: file_anovel_genai_v0_generation_get_proto_depIdxs,
		MessageInfos:      file_anovel_genai_v0_generation_get_proto_msgTypes,
	}.Build()
	File_anovel_genai_v0_generation_get_proto = out.File
	file_anovel_genai_v0_generation_get_proto_goTypes = nil
	file_anovel_genai_v0_generation_get_proto_depIdxs = nil
}
