// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: anovel/genai/v0/generation.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tier is the level of model capability a caller asks for. This service maps each Tier to a model
// and a reasoning effort for the configured provider; callers never name a model.
type Tier int32

const (
	// TIER_UNSPECIFIED is never valid in a request.
	Tier_TIER_UNSPECIFIED Tier = 0
	// TIER_FAST favours latency and cost.
	Tier_TIER_FAST Tier = 1
	// TIER_BALANCED trades capability against cost.
	Tier_TIER_BALANCED Tier = 2
	// TIER_DEEP favours capability.
	Tier_TIER_DEEP Tier = 3
)

// Enum value maps for Tier.
var (
	Tier_name = map[int32]string{
		0: "TIER_UNSPECIFIED",
		1: "TIER_FAST",
		2: "TIER_BALANCED",
		3: "TIER_DEEP",
	}
	Tier_value = map[string]int32{
		"TIER_UNSPECIFIED": 0,
		"TIER_FAST":        1,
		"TIER_BALANCED":    2,
		"TIER_DEEP":        3,
	}
)

func (x Tier) Enum() *Tier {
	p := new(Tier)
	*p = x
	return p
}

func (x Tier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Tier) Descriptor() protoreflect.EnumDescriptor {
	return file_anovel_genai_v0_generation_proto_enumTypes[0].Descriptor()
}

func (Tier) Type() protoreflect.EnumType {
	return &file_anovel_genai_v0_generation_proto_enumTypes[0]
}

func (x Tier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Tier.Descriptor instead.
func (Tier) EnumDescriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_proto_rawDescGZIP(), []int{0}
}

// GenerationFailure is what kind of failure ended a generation.
type GenerationFailure int32

const (
	// GENERATION_FAILURE_UNSPECIFIED means the generation did not fail.
	GenerationFailure_GENERATION_FAILURE_UNSPECIFIED GenerationFailure = 0
	// GENERATION_FAILURE_REFUSED means the model or the provider's policy declined the request.
	GenerationFailure_GENERATION_FAILURE_REFUSED GenerationFailure = 1
	// GENERATION_FAILURE_INCOMPLETE means the output stopped at the Tier's output ceiling.
	GenerationFailure_GENERATION_FAILURE_INCOMPLETE GenerationFailure = 2
	// GENERATION_FAILURE_INVALID_REQUEST means the provider rejected the request before running it,
	// for example an input over the context window or an unsupported output schema. It cost nothing.
	GenerationFailure_GENERATION_FAILURE_INVALID_REQUEST GenerationFailure = 3
	// GENERATION_FAILURE_FAILED is every other failure, including an unknown outcome.
	GenerationFailure_GENERATION_FAILURE_FAILED GenerationFailure = 4
)

// Enum value maps for GenerationFailure.
var (
	GenerationFailure_name = map[int32]string{
		0: "GENERATION_FAILURE_UNSPECIFIED",
		1: "GENERATION_FAILURE_REFUSED",
		2: "GENERATION_FAILURE_INCOMPLETE",
		3: "GENERATION_FAILURE_INVALID_REQUEST",
		4: "GENERATION_FAILURE_FAILED",
	}
	GenerationFailure_value = map[string]int32{
		"GENERATION_FAILURE_UNSPECIFIED":     0,
		"GENERATION_FAILURE_REFUSED":         1,
		"GENERATION_FAILURE_INCOMPLETE":      2,
		"GENERATION_FAILURE_INVALID_REQUEST": 3,
		"GENERATION_FAILURE_FAILED":          4,
	}
)

func (x GenerationFailure) Enum() *GenerationFailure {
	p := new(GenerationFailure)
	*p = x
	return p
}

func (x GenerationFailure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerationFailure) Descriptor() protoreflect.EnumDescriptor {
	return file_anovel_genai_v0_generation_proto_enumTypes[1].Descriptor()
}

func (GenerationFailure) Type() protoreflect.EnumType {
	return &file_anovel_genai_v0_generation_proto_enumTypes[1]
}

func (x GenerationFailure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerationFailure.Descriptor instead.
func (GenerationFailure) EnumDescriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_proto_rawDescGZIP(), []int{1}
}

// GenerationStatus is where a generation sits in its lifecycle.
type GenerationStatus int32

const (
	// GENERATION_STATUS_UNSPECIFIED means the status was not set. Never a value the service stores.
	GenerationStatus_GENERATION_STATUS_UNSPECIFIED GenerationStatus = 0
	// GENERATION_STATUS_PENDING means no provider call has been accepted for the current attempt yet.
	GenerationStatus_GENERATION_STATUS_PENDING GenerationStatus = 1
	// GENERATION_STATUS_RUNNING means the provider accepted the call and it has not settled yet.
	GenerationStatus_GENERATION_STATUS_RUNNING GenerationStatus = 2
	// GENERATION_STATUS_SUCCEEDED means the provider returned a usable output.
	GenerationStatus_GENERATION_STATUS_SUCCEEDED GenerationStatus = 3
	// GENERATION_STATUS_FAILED means the generation failed; its failure says how. A resend of the same
	// request runs again from scratch.
	GenerationStatus_GENERATION_STATUS_FAILED GenerationStatus = 4
	// GENERATION_STATUS_CANCELLED means the generation was stopped on the owner's request. A resend of
	// the same request runs again from scratch.
	GenerationStatus_GENERATION_STATUS_CANCELLED GenerationStatus = 6
)

// Enum value maps for GenerationStatus.
var (
	GenerationStatus_name = map[int32]string{
		0: "GENERATION_STATUS_UNSPECIFIED",
		1: "GENERATION_STATUS_PENDING",
		2: "GENERATION_STATUS_RUNNING",
		3: "GENERATION_STATUS_SUCCEEDED",
		4: "GENERATION_STATUS_FAILED",
		6: "GENERATION_STATUS_CANCELLED",
	}
	GenerationStatus_value = map[string]int32{
		"GENERATION_STATUS_UNSPECIFIED": 0,
		"GENERATION_STATUS_PENDING":     1,
		"GENERATION_STATUS_RUNNING":     2,
		"GENERATION_STATUS_SUCCEEDED":   3,
		"GENERATION_STATUS_FAILED":      4,
		"GENERATION_STATUS_CANCELLED":   6,
	}
)

func (x GenerationStatus) Enum() *GenerationStatus {
	p := new(GenerationStatus)
	*p = x
	return p
}

func (x GenerationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_anovel_genai_v0_generation_proto_enumTypes[2].Descriptor()
}

func (GenerationStatus) Type() protoreflect.EnumType {
	return &file_anovel_genai_v0_generation_proto_enumTypes[2]
}

func (x GenerationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerationStatus.Descriptor instead.
func (GenerationStatus) EnumDescriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_proto_rawDescGZIP(), []int{2}
}

// A Generation is one AI generative call as this service records it.
//
// The caller states what it wants in provider-neutral terms; this service composes the provider call,
// executes it durably, never pays for it twice, and reports what it consumed.
type Generation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// OwnerID is the user this acts for, formatted as a UUID. Supplied by the calling service.
	OwnerId string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Purpose is the caller's own label for what this spend is attributed to. Opaque here.
	Purpose string `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// Status is where the generation sits in its lifecycle.
	Status GenerationStatus `protobuf:"varint,4,opt,name=status,proto3,enum=anovel.genai.v0.GenerationStatus" json:"status,omitempty"`
	// Output is the JSON document conforming to the request's output schema. Empty until it succeeds.
	Output []byte `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"`
	// Error names the cause of a failure in this service's own words. Raw provider details remain in
	// server-side logs. Empty unless the generation failed or was cancelled.
	Error string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Creation timestamp, formatted as RFC 3339.
	CreatedAt string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of the most recent update, formatted as RFC 3339.
	UpdatedAt string `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Timestamp the generation reached a terminal status, formatted as RFC 3339. Empty until then.
	SettledAt string `protobuf:"bytes,11,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	// Timestamp the settled generation and its usage may be purged, formatted as RFC 3339.
	ExpiresAt string `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Failure says what kind of failure ended the generation, so the caller can decide what to do.
	// Unspecified unless the status is failed.
	Failure GenerationFailure `protobuf:"varint,14,opt,name=failure,proto3,enum=anovel.genai.v0.GenerationFailure" json:"failure,omitempty"`
	// Usage lists what each provider call consumed, failed ones included, with the model and effort
	// that actually ran. The caller keeps long-term usage; this record is purged with the generation.
	Usage         []*GenerationUsage `protobuf:"bytes,15,rep,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_anovel_genai_v0_generation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_proto_rawDescGZIP(), []int{0}
}

func (x *Generation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Generation) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Generation) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Generation) GetStatus() GenerationStatus {
	if x != nil {
		return x.Status
	}
	return GenerationStatus_GENERATION_STATUS_UNSPECIFIED
}

func (x *Generation) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Generation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Generation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Generation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Generation) GetSettledAt() string {
	if x != nil {
		return x.SettledAt
	}
	return ""
}

func (x *Generation) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *Generation) GetFailure() GenerationFailure {
	if x != nil {
		return x.Failure
	}
	return GenerationFailure_GENERATION_FAILURE_UNSPECIFIED
}

func (x *Generation) GetUsage() []*GenerationUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// GenerationUsage is what one provider call consumed. Totals include their detail counts, as the
// provider counts them.
type GenerationUsage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Attempt numbers the provider call within its generation, from one.
	Attempt int32 `protobuf:"varint,1,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Provider, Model and ReasoningEffort are what actually ran, read off the provider's response
	// rather than the Tier's preset. ReasoningEffort is empty for a model without one.
	Provider        string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Model           string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	ReasoningEffort string `protobuf:"bytes,4,opt,name=reasoning_effort,json=reasoningEffort,proto3" json:"reasoning_effort,omitempty"`
	// Totals include their detail counts, as the provider counts them.
	InputTokens int64 `protobuf:"varint,5,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	// CachedInputTokens were read from the provider's prompt cache, billed below the input rate.
	CachedInputTokens int64 `protobuf:"varint,6,opt,name=cached_input_tokens,json=cachedInputTokens,proto3" json:"cached_input_tokens,omitempty"`
	OutputTokens      int64 `protobuf:"varint,7,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ReasoningTokens   int64 `protobuf:"varint,8,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	// CacheWriteTokens were written to the provider's prompt cache, billed above the input rate.
	CacheWriteTokens int64 `protobuf:"varint,9,opt,name=cache_write_tokens,json=cacheWriteTokens,proto3" json:"cache_write_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerationUsage) Reset() {
	*x = GenerationUsage{}
	mi := &file_anovel_genai_v0_generation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationUsage) ProtoMessage() {}

func (x *GenerationUsage) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationUsage.ProtoReflect.Descriptor instead.
func (*GenerationUsage) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_proto_rawDescGZIP(), []int{1}
}

func (x *GenerationUsage) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *GenerationUsage) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GenerationUsage) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerationUsage) GetReasoningEffort() string {
	if x != nil {
		return x.ReasoningEffort
	}
	return ""
}

func (x *GenerationUsage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *GenerationUsage) GetCachedInputTokens() int64 {
	if x != nil {
		return x.CachedInputTokens
	}
	return 0
}

func (x *GenerationUsage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *GenerationUsage) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *GenerationUsage) GetCacheWriteTokens() int64 {
	if x != nil {
		return x.CacheWriteTokens
	}
	return 0
}

var File_anovel_genai_v0_generation_proto protoreflect.FileDescriptor

const file_anovel_genai_v0_generation_proto_rawDesc = "" +
	"\n" +
	" anovel/genai/v0/generation.proto\x12\x0fanovel.genai.v0\"\xe7\x03\n" +
	"\n" +
	"Generation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.anovel.genai.v0.GenerationStatusR\x06status\x12\x16\n" +
	"\x06output\x18\a \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"settled_at\x18\v \x01(\tR\tsettledAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\f \x01(\tR\texpiresAt\x12<\n" +
	"\afailure\x18\x0e \x01(\x0e2\".anovel.genai.v0.GenerationFailureR\afailure\x126\n" +
	"\x05usage\x18\x0f \x03(\v2 .anovel.genai.v0.GenerationUsageR\x05usageJ\x04\b\x05\x10\x06J\x04\b\x06\x10\aJ\x04\b\r\x10\x0eR\aattemptR\fmax_attemptsR\x10provider_call_id\"\xd9\x02\n" +
	"\x0fGenerationUsage\x12\x18\n" +
	"\aattempt\x18\x01 \x01(\x05R\aattempt\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12)\n" +
	"\x10reasoning_effort\x18\x04 \x01(\tR\x0freasoningEffort\x12!\n" +
	"\finput_tokens\x18\x05 \x01(\x03R\vinputTokens\x12.\n" +
	"\x13cached_input_tokens\x18\x06 \x01(\x03R\x11cachedInputTokens\x12#\n" +
	"\routput_tokens\x18\a \x01(\x03R\foutputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\b \x01(\x03R\x0freasoningTokens\x12,\n" +
	"\x12cache_write_tokens\x18\t \x01(\x03R\x10cacheWriteTokens*M\n" +
	"\x04Tier\x12\x14\n" +
	"\x10TIER_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTIER_FAST\x10\x01\x12\x11\n" +
	"\rTIER_BALANCED\x10\x02\x12\r\n" +
	"\tTIER_DEEP\x10\x03*\xc1\x01\n" +
	"\x11GenerationFailure\x12\"\n" +
	"\x1eGENERATION_FAILURE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aGENERATION_FAILURE_REFUSED\x10\x01\x12!\n" +
	"\x1dGENERATION_FAILURE_INCOMPLETE\x10\x02\x12&\n" +
	"\"GENERATION_FAILURE_INVALID_REQUEST\x10\x03\x12\x1d\n" +
	"\x19GENERATION_FAILURE_FAILED\x10\x04*\xf6\x01\n" +
	"\x10GenerationStatus\x12!\n" +
	"\x1dGENERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GENERATION_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19GENERATION_STATUS_RUNNING\x10\x02\x12\x1f\n" +
	"\x1bGENERATION_STATUS_SUCCEEDED\x10\x03\x12\x1c\n" +
	"\x18GENERATION_STATUS_FAILED\x10\x04\x12\x1f\n" +
	"\x1bGENERATION_STATUS_CANCELLED\x10\x06\"\x04\b\x05\x10\x05*\x1bGENERATION_STATUS_ABANDONEDB\xd1\x01\n" +
	"\x13com.anovel.genai.v0B\x0fGenerationProtoP\x01ZKgithub.com/a-novel/service-genai/internal/handlers/protogen/anovel/genai/v0\xa2\x02\x03AGV\xaa\x02\x0fAnovel.Genai.V0\xca\x02\x0fAnovel\\Genai\\V0\xe2\x02\x1bAnovel\\Genai\\V0\\GPBMetadata\xea\x02\x11Anovel::Genai::V0b\x06proto3"

var (
	file_anovel_genai_v0_generation_proto_rawDescOnce sync.Once
	file_anovel_genai_v0_generation_proto_rawDescData []byte
)

func file_anovel_genai_v0_generation_proto_rawDescGZIP() []byte {
	file_anovel_genai_v0_generation_proto_rawDescOnce.Do(func() {
		file_anovel_genai_v0_generation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_proto_rawDesc), len(file_anovel_genai_v0_generation_proto_rawDesc)))
	})
	return file_anovel_genai_v0_generation_proto_rawDescData
}

var file_anovel_genai_v0_generation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_anovel_genai_v0_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anovel_genai_v0_generation_proto_goTypes = []any{
	(Tier)(0),               // 0: anovel.genai.v0.Tier
	(GenerationFailure)(0),  // 1: anovel.genai.v0.GenerationFailure
	(GenerationStatus)(0),   // 2: anovel.genai.v0.GenerationStatus
	(*Generation)(nil),      // 3: anovel.genai.v0.Generation
	(*GenerationUsage)(nil), // 4: anovel.genai.v0.GenerationUsage
}
var file_anovel_genai_v0_generation_proto_depIdxs = []int32{
	2, // 0: anovel.genai.v0.Generation.status:type_name -> anovel.genai.v0.GenerationStatus
	1, // 1: anovel.genai.v0.Generation.failure:type_name -> anovel.genai.v0.GenerationFailure
	4, // 2: anovel.genai.v0.Generation.usage:type_name -> anovel.genai.v0.GenerationUsage
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_anovel_genai_v0_generation_proto_init() }
func file_anovel_genai_v0_generation_proto_init() {
	if File_anovel_genai_v0_generation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_proto_rawDesc), len(file_anovel_genai_v0_generation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anovel_genai_v0_generation_proto_goTypes,
		DependencyIndexes: file_anovel_genai_v0_generation_proto_depIdxs,
		EnumInfos:         file_anovel_genai_v0_generation_proto_enumTypes,
		MessageInfos:      file_anovel_genai_v0_generation_proto_msgTypes,
	}.Build()
	File_anovel_genai_v0_generation_proto = out.File
	file_anovel_genai_v0_generation_proto_goTypes = nil
	file_anovel_genai_v0_generation_proto_depIdxs = nil
}
