// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: anovel/genai/v0/generation_submit.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerationSubmitRequest carries a new generation. The server mints the id and the timestamps.
type GenerationSubmitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OwnerID is the user this acts for, formatted as a UUID. Supplied by the calling service, which
	// verified it against its own credential — this service does not authenticate.
	OwnerId string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Purpose labels what the spend is attributed to. Required, and otherwise opaque: the vocabulary
	// belongs to the caller.
	Purpose string `protobuf:"bytes,2,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// Tier is the level of model capability wanted. Required.
	Tier Tier `protobuf:"varint,6,opt,name=tier,proto3,enum=anovel.genai.v0.Tier" json:"tier,omitempty"`
	// Instructions are the trusted channel: the caller's own directions to the model. Required.
	Instructions string `protobuf:"bytes,7,opt,name=instructions,proto3" json:"instructions,omitempty"`
	// Input is the untrusted channel: user content as any JSON value. Required.
	Input []byte `protobuf:"bytes,8,opt,name=input,proto3" json:"input,omitempty"`
	// OutputSchema is the JSON Schema the output must conform to, within OpenAI's strict-mode subset.
	// Required. Instructions, input and schema together are at most 3,688,000 bytes.
	OutputSchema []byte `protobuf:"bytes,9,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	// Variant asks for another generation of a request that already succeeded, such as a regenerate.
	// Zero by default. A caller recovering from a crash counts variants from zero again, and each one
	// already run returns its stored result.
	Variant       uint32 `protobuf:"varint,10,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationSubmitRequest) Reset() {
	*x = GenerationSubmitRequest{}
	mi := &file_anovel_genai_v0_generation_submit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationSubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationSubmitRequest) ProtoMessage() {}

func (x *GenerationSubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_submit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationSubmitRequest.ProtoReflect.Descriptor instead.
func (*GenerationSubmitRequest) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_submit_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationSubmitRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GenerationSubmitRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *GenerationSubmitRequest) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *GenerationSubmitRequest) GetInstructions() string {
	if x != nil {
		return x.Instructions
	}
	return ""
}

func (x *GenerationSubmitRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *GenerationSubmitRequest) GetOutputSchema() []byte {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *GenerationSubmitRequest) GetVariant() uint32 {
	if x != nil {
		return x.Variant
	}
	return 0
}

// GenerationSubmitResponse returns the recorded generation and whether this call created it.
type GenerationSubmitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generation is the recorded generation — the newly created one, or the existing one on a replay.
	Generation *Generation `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// Created is false when a pending, running or succeeded generation of the same request was returned, so a
	// caller resending after a lost connection attaches to work already paid for.
	Created       bool `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationSubmitResponse) Reset() {
	*x = GenerationSubmitResponse{}
	mi := &file_anovel_genai_v0_generation_submit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationSubmitResponse) ProtoMessage() {}

func (x *GenerationSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_generation_submit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationSubmitResponse.ProtoReflect.Descriptor instead.
func (*GenerationSubmitResponse) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_generation_submit_proto_rawDescGZIP(), []int{1}
}

func (x *GenerationSubmitResponse) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *GenerationSubmitResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

var File_anovel_genai_v0_generation_submit_proto protoreflect.FileDescriptor

const file_anovel_genai_v0_generation_submit_proto_rawDesc = "" +
	"\n" +
	"'anovel/genai/v0/generation_submit.proto\x12\x0fanovel.genai.v0\x1a anovel/genai/v0/generation.proto\"\xac\x02\n" +
	"\x17GenerationSubmitRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x18\n" +
	"\apurpose\x18\x02 \x01(\tR\apurpose\x12)\n" +
	"\x04tier\x18\x06 \x01(\x0e2\x15.anovel.genai.v0.TierR\x04tier\x12\"\n" +
	"\finstructions\x18\a \x01(\tR\finstructions\x12\x14\n" +
	"\x05input\x18\b \x01(\fR\x05input\x12#\n" +
	"\routput_schema\x18\t \x01(\fR\foutputSchema\x12\x18\n" +
	"\avariant\x18\n" +
	" \x01(\rR\avariantJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\x0fidempotency_keyR\arequestR\fmax_attempts\"q\n" +
	"\x18GenerationSubmitResponse\x12;\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x1b.anovel.genai.v0.GenerationR\n" +
	"generation\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated2\x82\x01\n" +
	"\x17GenerationSubmitService\x12g\n" +
	"\x10GenerationSubmit\x12(.anovel.genai.v0.GenerationSubmitRequest\x1a).anovel.genai.v0.GenerationSubmitResponseB\xd7\x01\n" +
	"\x13com.anovel.genai.v0B\x15GenerationSubmitProtoP\x01ZKgithub.com/a-novel/service-genai/internal/handlers/protogen/anovel/genai/v0\xa2\x02\x03AGV\xaa\x02\x0fAnovel.Genai.V0\xca\x02\x0fAnovel\\Genai\\V0\xe2\x02\x1bAnovel\\Genai\\V0\\GPBMetadata\xea\x02\x11Anovel::Genai::V0b\x06proto3"

var (
	file_anovel_genai_v0_generation_submit_proto_rawDescOnce sync.Once
	file_anovel_genai_v0_generation_submit_proto_rawDescData []byte
)

func file_anovel_genai_v0_generation_submit_proto_rawDescGZIP() []byte {
	file_anovel_genai_v0_generation_submit_proto_rawDescOnce.Do(func() {
		file_anovel_genai_v0_generation_submit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_submit_proto_rawDesc), len(file_anovel_genai_v0_generation_submit_proto_rawDesc)))
	})
	return file_anovel_genai_v0_generation_submit_proto_rawDescData
}

var file_anovel_genai_v0_generation_submit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_anovel_genai_v0_generation_submit_proto_goTypes = []any{
	(*GenerationSubmitRequest)(nil),  // 0: anovel.genai.v0.GenerationSubmitRequest
	(*GenerationSubmitResponse)(nil), // 1: anovel.genai.v0.GenerationSubmitResponse
	(Tier)(0),                        // 2: anovel.genai.v0.Tier
	(*Generation)(nil),               // 3: anovel.genai.v0.Generation
}
var file_anovel_genai_v0_generation_submit_proto_depIdxs = []int32{
	2, // 0: anovel.genai.v0.GenerationSubmitRequest.tier:type_name -> anovel.genai.v0.Tier
	3, // 1: anovel.genai.v0.GenerationSubmitResponse.generation:type_name -> anovel.genai.v0.Generation
	0, // 2: anovel.genai.v0.GenerationSubmitService.GenerationSubmit:input_type -> anovel.genai.v0.GenerationSubmitRequest
	1, // 3: anovel.genai.v0.GenerationSubmitService.GenerationSubmit:output_type -> anovel.genai.v0.GenerationSubmitResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_anovel_genai_v0_generation_submit_proto_init() }
func file_anovel_genai_v0_generation_submit_proto_init() {
	if File_anovel_genai_v0_generation_submit_proto != nil {
		return
	}
	file_anovel_genai_v0_generation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_generation_submit_proto_rawDesc), len(file_anovel_genai_v0_generation_submit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anovel_genai_v0_generation_submit_proto_goTypes,
		DependencyIndexes: file_anovel_genai_v0_generation_submit_proto_depIdxs,
		MessageInfos:      file_anovel_genai_v0_generation_submit_proto_msgTypes,
	}.Build()
	File_anovel_genai_v0_generation_submit_proto = out.File
	file_anovel_genai_v0_generation_submit_proto_goTypes = nil
	file_anovel_genai_v0_generation_submit_proto_depIdxs = nil
}
