// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: anovel/genai/v0/generation_cancel.proto

package v0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenerationCancelService_GenerationCancel_FullMethodName = "/anovel.genai.v0.GenerationCancelService/GenerationCancel"
)

// GenerationCancelServiceClient is the client API for GenerationCancelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GenerationCancelService stops a generation so an abandoned one stops costing.
//
// It records the request and returns. The worker holding the generation observes it, stops the
// provider operation, and settles — recording whatever was consumed before the stop, because a
// cancelled call is not a free one.
type GenerationCancelServiceClient interface {
	GenerationCancel(ctx context.Context, in *GenerationCancelRequest, opts ...grpc.CallOption) (*GenerationCancelResponse, error)
}

type generationCancelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerationCancelServiceClient(cc grpc.ClientConnInterface) GenerationCancelServiceClient {
	return &generationCancelServiceClient{cc}
}

func (c *generationCancelServiceClient) GenerationCancel(ctx context.Context, in *GenerationCancelRequest, opts ...grpc.CallOption) (*GenerationCancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationCancelResponse)
	err := c.cc.Invoke(ctx, GenerationCancelService_GenerationCancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerationCancelServiceServer is the server API for GenerationCancelService service.
// All implementations must embed UnimplementedGenerationCancelServiceServer
// for forward compatibility.
//
// GenerationCancelService stops a generation so an abandoned one stops costing.
//
// It records the request and returns. The worker holding the generation observes it, stops the
// provider operation, and settles — recording whatever was consumed before the stop, because a
// cancelled call is not a free one.
type GenerationCancelServiceServer interface {
	GenerationCancel(context.Context, *GenerationCancelRequest) (*GenerationCancelResponse, error)
	mustEmbedUnimplementedGenerationCancelServiceServer()
}

// UnimplementedGenerationCancelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerationCancelServiceServer struct{}

func (UnimplementedGenerationCancelServiceServer) GenerationCancel(context.Context, *GenerationCancelRequest) (*GenerationCancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerationCancel not implemented")
}
func (UnimplementedGenerationCancelServiceServer) mustEmbedUnimplementedGenerationCancelServiceServer() {
}
func (UnimplementedGenerationCancelServiceServer) testEmbeddedByValue() {}

// UnsafeGenerationCancelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerationCancelServiceServer will
// result in compilation errors.
type UnsafeGenerationCancelServiceServer interface {
	mustEmbedUnimplementedGenerationCancelServiceServer()
}

func RegisterGenerationCancelServiceServer(s grpc.ServiceRegistrar, srv GenerationCancelServiceServer) {
	// If the following call panics, it indicates UnimplementedGenerationCancelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenerationCancelService_ServiceDesc, srv)
}

func _GenerationCancelService_GenerationCancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerationCancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerationCancelServiceServer).GenerationCancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenerationCancelService_GenerationCancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerationCancelServiceServer).GenerationCancel(ctx, req.(*GenerationCancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenerationCancelService_ServiceDesc is the grpc.ServiceDesc for GenerationCancelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenerationCancelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anovel.genai.v0.GenerationCancelService",
	HandlerType: (*GenerationCancelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerationCancel",
			Handler:    _GenerationCancelService_GenerationCancel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anovel/genai/v0/generation_cancel.proto",
}
