// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: anovel/genai/v0/tier_list.proto

package v0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TierListService_TierList_FullMethodName = "/anovel.genai.v0.TierListService/TierList"
)

// TierListServiceClient is the client API for TierListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TierListService tells callers how large a request each Tier takes, so a caller can fit its input
// and its output schema before submitting. It never names the model behind a Tier.
type TierListServiceClient interface {
	TierList(ctx context.Context, in *TierListRequest, opts ...grpc.CallOption) (*TierListResponse, error)
}

type tierListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTierListServiceClient(cc grpc.ClientConnInterface) TierListServiceClient {
	return &tierListServiceClient{cc}
}

func (c *tierListServiceClient) TierList(ctx context.Context, in *TierListRequest, opts ...grpc.CallOption) (*TierListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TierListResponse)
	err := c.cc.Invoke(ctx, TierListService_TierList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TierListServiceServer is the server API for TierListService service.
// All implementations must embed UnimplementedTierListServiceServer
// for forward compatibility.
//
// TierListService tells callers how large a request each Tier takes, so a caller can fit its input
// and its output schema before submitting. It never names the model behind a Tier.
type TierListServiceServer interface {
	TierList(context.Context, *TierListRequest) (*TierListResponse, error)
	mustEmbedUnimplementedTierListServiceServer()
}

// UnimplementedTierListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTierListServiceServer struct{}

func (UnimplementedTierListServiceServer) TierList(context.Context, *TierListRequest) (*TierListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TierList not implemented")
}
func (UnimplementedTierListServiceServer) mustEmbedUnimplementedTierListServiceServer() {}
func (UnimplementedTierListServiceServer) testEmbeddedByValue()                         {}

// UnsafeTierListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TierListServiceServer will
// result in compilation errors.
type UnsafeTierListServiceServer interface {
	mustEmbedUnimplementedTierListServiceServer()
}

func RegisterTierListServiceServer(s grpc.ServiceRegistrar, srv TierListServiceServer) {
	// If the following call panics, it indicates UnimplementedTierListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TierListService_ServiceDesc, srv)
}

func _TierListService_TierList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TierListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TierListServiceServer).TierList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TierListService_TierList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TierListServiceServer).TierList(ctx, req.(*TierListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TierListService_ServiceDesc is the grpc.ServiceDesc for TierListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TierListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anovel.genai.v0.TierListService",
	HandlerType: (*TierListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TierList",
			Handler:    _TierListService_TierList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anovel/genai/v0/tier_list.proto",
}
