// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: anovel/genai/v0/tier_list.proto

package v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TierListRequest takes no parameters.
type TierListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TierListRequest) Reset() {
	*x = TierListRequest{}
	mi := &file_anovel_genai_v0_tier_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierListRequest) ProtoMessage() {}

func (x *TierListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_tier_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierListRequest.ProtoReflect.Descriptor instead.
func (*TierListRequest) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_tier_list_proto_rawDescGZIP(), []int{0}
}

// TierCeilings is how many tokens one Tier accepts.
type TierCeilings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Tier  Tier                   `protobuf:"varint,1,opt,name=tier,proto3,enum=anovel.genai.v0.Tier" json:"tier,omitempty"`
	// MaxInputTokens is the most input the Tier's model accepts. Advertised, not enforced: a request
	// over it fails as an invalid request, at no cost.
	MaxInputTokens int64 `protobuf:"varint,2,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`
	// MaxOutputTokens caps the output, reasoning included.
	MaxOutputTokens int64 `protobuf:"varint,3,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TierCeilings) Reset() {
	*x = TierCeilings{}
	mi := &file_anovel_genai_v0_tier_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierCeilings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierCeilings) ProtoMessage() {}

func (x *TierCeilings) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_tier_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierCeilings.ProtoReflect.Descriptor instead.
func (*TierCeilings) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_tier_list_proto_rawDescGZIP(), []int{1}
}

func (x *TierCeilings) GetTier() Tier {
	if x != nil {
		return x.Tier
	}
	return Tier_TIER_UNSPECIFIED
}

func (x *TierCeilings) GetMaxInputTokens() int64 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

func (x *TierCeilings) GetMaxOutputTokens() int64 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

// TierListResponse lists every Tier, in capability order.
type TierListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tiers         []*TierCeilings        `protobuf:"bytes,1,rep,name=tiers,proto3" json:"tiers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TierListResponse) Reset() {
	*x = TierListResponse{}
	mi := &file_anovel_genai_v0_tier_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TierListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TierListResponse) ProtoMessage() {}

func (x *TierListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v0_tier_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TierListResponse.ProtoReflect.Descriptor instead.
func (*TierListResponse) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v0_tier_list_proto_rawDescGZIP(), []int{2}
}

func (x *TierListResponse) GetTiers() []*TierCeilings {
	if x != nil {
		return x.Tiers
	}
	return nil
}

var File_anovel_genai_v0_tier_list_proto protoreflect.FileDescriptor

const file_anovel_genai_v0_tier_list_proto_rawDesc = "" +
	"\n" +
	"\x1fanovel/genai/v0/tier_list.proto\x12\x0fanovel.genai.v0\x1a anovel/genai/v0/generation.proto\"\x11\n" +
	"\x0fTierListRequest\"\x8f\x01\n" +
	"\fTierCeilings\x12)\n" +
	"\x04tier\x18\x01 \x01(\x0e2\x15.anovel.genai.v0.TierR\x04tier\x12(\n" +
	"\x10max_input_tokens\x18\x02 \x01(\x03R\x0emaxInputTokens\x12*\n" +
	"\x11max_output_tokens\x18\x03 \x01(\x03R\x0fmaxOutputTokens\"G\n" +
	"\x10TierListResponse\x123\n" +
	"\x05tiers\x18\x01 \x03(\v2\x1d.anovel.genai.v0.TierCeilingsR\x05tiers2b\n" +
	"\x0fTierListService\x12O\n" +
	"\bTierList\x12 .anovel.genai.v0.TierListRequest\x1a!.anovel.genai.v0.TierListResponseB\xcf\x01\n" +
	"\x13com.anovel.genai.v0B\rTierListProtoP\x01ZKgithub.com/a-novel/service-genai/internal/handlers/protogen/anovel/genai/v0\xa2\x02\x03AGV\xaa\x02\x0fAnovel.Genai.V0\xca\x02\x0fAnovel\\Genai\\V0\xe2\x02\x1bAnovel\\Genai\\V0\\GPBMetadata\xea\x02\x11Anovel::Genai::V0b\x06proto3"

var (
	file_anovel_genai_v0_tier_list_proto_rawDescOnce sync.Once
	file_anovel_genai_v0_tier_list_proto_rawDescData []byte
)

func file_anovel_genai_v0_tier_list_proto_rawDescGZIP() []byte {
	file_anovel_genai_v0_tier_list_proto_rawDescOnce.Do(func() {
		file_anovel_genai_v0_tier_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_tier_list_proto_rawDesc), len(file_anovel_genai_v0_tier_list_proto_rawDesc)))
	})
	return file_anovel_genai_v0_tier_list_proto_rawDescData
}

var file_anovel_genai_v0_tier_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_anovel_genai_v0_tier_list_proto_goTypes = []any{
	(*TierListRequest)(nil),  // 0: anovel.genai.v0.TierListRequest
	(*TierCeilings)(nil),     // 1: anovel.genai.v0.TierCeilings
	(*TierListResponse)(nil), // 2: anovel.genai.v0.TierListResponse
	(Tier)(0),                // 3: anovel.genai.v0.Tier
}
var file_anovel_genai_v0_tier_list_proto_depIdxs = []int32{
	3, // 0: anovel.genai.v0.TierCeilings.tier:type_name -> anovel.genai.v0.Tier
	1, // 1: anovel.genai.v0.TierListResponse.tiers:type_name -> anovel.genai.v0.TierCeilings
	0, // 2: anovel.genai.v0.TierListService.TierList:input_type -> anovel.genai.v0.TierListRequest
	2, // 3: anovel.genai.v0.TierListService.TierList:output_type -> anovel.genai.v0.TierListResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_anovel_genai_v0_tier_list_proto_init() }
func file_anovel_genai_v0_tier_list_proto_init() {
	if File_anovel_genai_v0_tier_list_proto != nil {
		return
	}
	file_anovel_genai_v0_generation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_genai_v0_tier_list_proto_rawDesc), len(file_anovel_genai_v0_tier_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anovel_genai_v0_tier_list_proto_goTypes,
		DependencyIndexes: file_anovel_genai_v0_tier_list_proto_depIdxs,
		MessageInfos:      file_anovel_genai_v0_tier_list_proto_msgTypes,
	}.Build()
	File_anovel_genai_v0_tier_list_proto = out.File
	file_anovel_genai_v0_tier_list_proto_goTypes = nil
	file_anovel_genai_v0_tier_list_proto_depIdxs = nil
}
