-- The service's two tables, and the split between them is the point of the design.
--
-- generations is the execution record. It holds the prompt and the output, which are user content,
-- so it is purged on a retention schedule and an erasure request reaches it.
--
-- generation_ledger is the cost record. It holds no user content, so it is never purged and an
-- erasure request does not touch it. That separation is what lets the audit trail outlive the
-- material it describes, and it is why there is no foreign key between the two: the parent row is
-- deleted while the ledger row must survive.
CREATE TYPE generation_status AS ENUM(
  'pending',
  'running',
  'succeeded',
  'failed',
  'abandoned',
  'cancelled'
);

-- Several column choices depart from the service scaffold. Each departure is load-bearing:
--
--   * Timestamps are full precision and generated by the database with clock_timestamp(). The
--     scaffold's timestamp(0) cannot order two events inside the same second, which a lease and a
--     settle routinely are. CURRENT_TIMESTAMP and now() are frozen at transaction start, so a
--     column written inside a transaction could never advance past the value its neighbours already
--     hold. The database is the single clock, so worker clock skew never enters lease arithmetic.
--   * Identifiers are time-ordered (uuidv7, native to the PostgreSQL 18 image this service pins),
--     so a table with heavy insert churn keeps index locality.
--   * status is a database enum. The value set changes rarely, and when it does a migration on the
--     type is what keeps every column consistent — a text column with a CHECK cannot.
CREATE TABLE generations (
  id uuid PRIMARY KEY NOT NULL DEFAULT uuidv7(),
  /* The user the generation acts for, supplied by the calling service. Every read is scoped by it
  inside the statement, so a caller that omits it fails to scan rather than returning another
  owner's row. It is also the attribution key for cost. */
  owner_id uuid NOT NULL,
  /* Why the platform spent this money, from a closed vocabulary the core layer owns. Validated
  there rather than here: the vocabulary gains entries faster than a migration should run. */
  purpose text NOT NULL CHECK (purpose <> ''),
  /* The abstract execution tier, from a closed vocabulary the core layer resolves to a provider,
  a model and its parameters. Callers never name a model. */
  profile text NOT NULL CHECK (profile <> ''),
  /* NOT NULL, unlike the generic queue this is derived from. In a service whose only workload is a
  priced call, an unkeyed submission is a bug the schema should refuse rather than a default it
  tolerates. */
  idempotency_key text NOT NULL CHECK (idempotency_key <> ''),
  /* Digest of the request body. A key reused with a different request is a conflict, not a replay;
  NOT NULL so that comparison can never pass on a null stored side. */
  request_fingerprint bytea NOT NULL,
  /* The provider-agnostic generation request: instructions, input, output schema, ceilings. User
  content, and the reason this table is purged. */
  request jsonb NOT NULL CHECK (jsonb_typeof(request) = 'object'),
  /* The provider's structured output. Null until the generation succeeds. User content. */
  output jsonb CHECK (
    output IS NULL
    OR jsonb_typeof(output) = 'object'
  ),
  /* The structured failure on a terminal failure. Null otherwise. */
  error jsonb CHECK (
    error IS NULL
    OR jsonb_typeof(error) = 'object'
  ),
  status generation_status NOT NULL DEFAULT 'pending',
  attempt smallint NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  /* One attempt by default, which is the right floor for a priced call. */
  max_attempts smallint NOT NULL DEFAULT 1 CHECK (max_attempts >= 1),
  run_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  lease_expires_at timestamp with time zone,
  claimed_by text CHECK (
    claimed_by IS NULL
    OR claimed_by <> ''
  ),
  /* Ships ahead of the endpoint that writes it. The claim predicate sits behind a partial index on
  the hot path, and changing that predicate later means re-reasoning about the index on a table
  holding live rows. */
  cancel_requested_at timestamp with time zone,
  /* The provider's own identifier for the operation this generation started. It is what lets a
  generation whose worker died mid-call re-attach to that operation instead of paying for a second
  one. */
  provider_call_id text CHECK (
    provider_call_id IS NULL
    OR provider_call_id <> ''
  ),
  created_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  settled_at timestamp with time zone,
  expires_at timestamp with time zone,
  -- A lease exists exactly when the generation is running. The equality binds both directions: a
  -- running row without a lease, and a lease on a row in any other status, are both rejected.
  CONSTRAINT generations_lease_matches_status CHECK (
    (status = 'running') = (lease_expires_at IS NOT NULL)
  ),
  -- The settled and expiry timestamps are set exactly when the status is terminal. A partial write
  -- that settles the status without stamping both, or stamps them on a still-running generation, is
  -- rejected by the database rather than by application code.
  CONSTRAINT generations_terminal_fields CHECK (
    (
      status IN ('succeeded', 'failed', 'abandoned', 'cancelled')
    ) = (
      settled_at IS NOT NULL
      AND expires_at IS NOT NULL
    )
  )
);

-- purpose is part of the key. Without a second dimension, one owner's keys collide across features
-- and a submission from the recommender is treated as a replay of one from the studio.
CREATE UNIQUE INDEX generations_idempotency_idx ON generations (owner_id, purpose, idempotency_key);

-- Each partial index matches the predicate that will run against it, so none of them grows as
-- terminal rows accumulate and no hot path degrades over the life of the table.
CREATE INDEX generations_dispatch_idx ON generations (run_at)
WHERE
  status = 'pending';

CREATE INDEX generations_lease_idx ON generations (lease_expires_at)
WHERE
  status = 'running';

CREATE INDEX generations_retention_idx ON generations (expires_at)
WHERE
  expires_at IS NOT NULL;

CREATE INDEX generations_owner_idx ON generations (owner_id, created_at DESC);

-- Continuous insert-update-delete churn is what kills database-backed queues: under the defaults,
-- dead tuples accumulate faster than the table is vacuumed and the claim query slows down with no
-- other symptom.
ALTER TABLE generations
SET
  (
    autovacuum_vacuum_scale_factor = 0.02,
    autovacuum_vacuum_threshold = 25,
    autovacuum_analyze_scale_factor = 0.02
  );

-- One row per attempt, not per generation: a retry that burned tokens twice cost twice, and both
-- charges have to exist. The columns duplicate owner_id, purpose and profile from generations
-- rather than joining to it, because the row this would join to is deleted by the retention purge
-- while this row is kept.
CREATE TABLE generation_ledger (
  generation_id uuid NOT NULL,
  /* The attempt this charge belongs to. Attempts are one-based here: a row exists only once a run
  has begun, so attempt zero can never have consumed anything. */
  attempt smallint NOT NULL CHECK (attempt >= 1),
  owner_id uuid NOT NULL,
  purpose text NOT NULL CHECK (purpose <> ''),
  profile text NOT NULL CHECK (profile <> ''),
  /* What actually ran, resolved from the profile at execution time. Recorded rather than derived,
  because the profile's resolution changes as models are swapped underneath it. */
  provider text NOT NULL CHECK (provider <> ''),
  model text NOT NULL CHECK (model <> ''),
  /* Total input tokens, cached ones included — this mirrors the provider's own accounting rather
  than correcting it, so a row can be checked against an invoice line without arithmetic. */
  input_tokens bigint NOT NULL CHECK (input_tokens >= 0),
  /* The subset of input_tokens served from the provider's cache, billed at a lower rate. */
  cached_input_tokens bigint NOT NULL DEFAULT 0 CHECK (cached_input_tokens >= 0),
  /* Total output tokens, reasoning ones included. */
  output_tokens bigint NOT NULL CHECK (output_tokens >= 0),
  /* The subset of output_tokens the model spent on reasoning. Billed at the output rate, so it is
  recorded for visibility and never priced as a separate line — doing so would double-count it. */
  reasoning_tokens bigint NOT NULL DEFAULT 0 CHECK (reasoning_tokens >= 0),
  /* Prices in force when this attempt settled, in currency per million tokens — the unit every
  provider publishes, so a row can be checked against a public price sheet directly. They are
  snapshotted onto the row rather than referenced by key: a later price change must not be able to
  rewrite what a past call cost. */
  input_price_per_mtoken numeric(20, 12) NOT NULL CHECK (input_price_per_mtoken >= 0),
  cached_input_price_per_mtoken numeric(20, 12) NOT NULL CHECK (cached_input_price_per_mtoken >= 0),
  output_price_per_mtoken numeric(20, 12) NOT NULL CHECK (output_price_per_mtoken >= 0),
  /* Identifies the price book those rates came from, so a disputed row can be traced to the commit
  that set them. */
  price_book_version text NOT NULL CHECK (price_book_version <> ''),
  /* ISO 4217. Constrained to the shape, not to a value, so a second billing currency does not need
  a migration on a table that must never lose history. */
  currency text NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
  /* What this attempt cost, computed from the token counts and the rates above. numeric, never a
  floating point type: a float cannot represent a cent exactly, and this column is money. */
  cost numeric(20, 8) NOT NULL CHECK (cost >= 0),
  created_at timestamp with time zone NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT generation_ledger_pkey PRIMARY KEY (generation_id, attempt),
  -- Each detail count is a subset of the total it is drawn from, in the provider's own accounting.
  -- Violating either means the usage was mapped wrong, and a wrong mapping silently misprices.
  CONSTRAINT generation_ledger_cached_within_input CHECK (cached_input_tokens <= input_tokens),
  CONSTRAINT generation_ledger_reasoning_within_output CHECK (reasoning_tokens <= output_tokens)
);

-- The two slices the usage read surface serves: an owner's total spend over a window, and the same
-- split by the purpose a monetization layer bills on.
CREATE INDEX generation_ledger_owner_idx ON generation_ledger (owner_id, created_at DESC);

CREATE INDEX generation_ledger_owner_purpose_idx ON generation_ledger (owner_id, purpose, created_at DESC);
