// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremocks

import (
	"context"

	"github.com/a-novel/service-genai/internal/core"
	"github.com/a-novel/service-genai/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenerationCancelDao creates a new instance of MockGenerationCancelDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCancelDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCancelDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCancelDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCancelDao is an autogenerated mock type for the GenerationCancelDao type
type MockGenerationCancelDao struct {
	mock.Mock
}

type MockGenerationCancelDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCancelDao) EXPECT() *MockGenerationCancelDao_Expecter {
	return &MockGenerationCancelDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCancelDao
func (_mock *MockGenerationCancelDao) Exec(ctx context.Context, request *dao.GenerationRequestCancelRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRequestCancelRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRequestCancelRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationRequestCancelRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCancelDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCancelDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationRequestCancelRequest
func (_e *MockGenerationCancelDao_Expecter) Exec(ctx any, request any) *MockGenerationCancelDao_Exec_Call {
	return &MockGenerationCancelDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCancelDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationRequestCancelRequest)) *MockGenerationCancelDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationRequestCancelRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationRequestCancelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCancelDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCancelDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCancelDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationRequestCancelRequest) (*dao.Generation, error)) *MockGenerationCancelDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCancelUsageListDao creates a new instance of MockGenerationCancelUsageListDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCancelUsageListDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCancelUsageListDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCancelUsageListDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCancelUsageListDao is an autogenerated mock type for the GenerationCancelUsageListDao type
type MockGenerationCancelUsageListDao struct {
	mock.Mock
}

type MockGenerationCancelUsageListDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCancelUsageListDao) EXPECT() *MockGenerationCancelUsageListDao_Expecter {
	return &MockGenerationCancelUsageListDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCancelUsageListDao
func (_mock *MockGenerationCancelUsageListDao) Exec(ctx context.Context, request *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.GenerationUsage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageListRequest) []*dao.GenerationUsage); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.GenerationUsage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationUsageListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCancelUsageListDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCancelUsageListDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationUsageListRequest
func (_e *MockGenerationCancelUsageListDao_Expecter) Exec(ctx any, request any) *MockGenerationCancelUsageListDao_Exec_Call {
	return &MockGenerationCancelUsageListDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCancelUsageListDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationUsageListRequest)) *MockGenerationCancelUsageListDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationUsageListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationUsageListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCancelUsageListDao_Exec_Call) Return(generationUsages []*dao.GenerationUsage, err error) *MockGenerationCancelUsageListDao_Exec_Call {
	_c.Call.Return(generationUsages, err)
	return _c
}

func (_c *MockGenerationCancelUsageListDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error)) *MockGenerationCancelUsageListDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCancelServiceCheck creates a new instance of MockGenerationCancelServiceCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCancelServiceCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCancelServiceCheck {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCancelServiceCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCancelServiceCheck is an autogenerated mock type for the GenerationCancelServiceCheck type
type MockGenerationCancelServiceCheck struct {
	mock.Mock
}

type MockGenerationCancelServiceCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCancelServiceCheck) EXPECT() *MockGenerationCancelServiceCheck_Expecter {
	return &MockGenerationCancelServiceCheck_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCancelServiceCheck
func (_mock *MockGenerationCancelServiceCheck) Exec(ctx context.Context, request *core.GenerationCheckRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCheckRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCheckRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationCheckRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCancelServiceCheck_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCancelServiceCheck_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationCheckRequest
func (_e *MockGenerationCancelServiceCheck_Expecter) Exec(ctx any, request any) *MockGenerationCancelServiceCheck_Exec_Call {
	return &MockGenerationCancelServiceCheck_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCancelServiceCheck_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationCheckRequest)) *MockGenerationCancelServiceCheck_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationCheckRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationCheckRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCancelServiceCheck_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCancelServiceCheck_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCancelServiceCheck_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationCheckRequest) (*dao.Generation, error)) *MockGenerationCancelServiceCheck_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCheckLogger creates a new instance of MockGenerationCheckLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckLogger {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckLogger is an autogenerated mock type for the GenerationCheckLogger type
type MockGenerationCheckLogger struct {
	mock.Mock
}

type MockGenerationCheckLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckLogger) EXPECT() *MockGenerationCheckLogger_Expecter {
	return &MockGenerationCheckLogger_Expecter{mock: &_m.Mock}
}

// Err provides a mock function for the type MockGenerationCheckLogger
func (_mock *MockGenerationCheckLogger) Err(ctx context.Context, msg string, fields ...any) {
	if len(fields) > 0 {
		_mock.Called(ctx, msg, fields)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockGenerationCheckLogger_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockGenerationCheckLogger_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - fields ...any
func (_e *MockGenerationCheckLogger_Expecter) Err(ctx any, msg any, fields ...any) *MockGenerationCheckLogger_Err_Call {
	return &MockGenerationCheckLogger_Err_Call{Call: _e.mock.On("Err",
		append([]any{ctx, msg}, fields...)...)}
}

func (_c *MockGenerationCheckLogger_Err_Call) Run(run func(ctx context.Context, msg string, fields ...any)) *MockGenerationCheckLogger_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockGenerationCheckLogger_Err_Call) Return() *MockGenerationCheckLogger_Err_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockGenerationCheckLogger_Err_Call) RunAndReturn(run func(ctx context.Context, msg string, fields ...any)) *MockGenerationCheckLogger_Err_Call {
	_c.Run(run)
	return _c
}

// NewMockGenerationCheckBeginStartDao creates a new instance of MockGenerationCheckBeginStartDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckBeginStartDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckBeginStartDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckBeginStartDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckBeginStartDao is an autogenerated mock type for the GenerationCheckBeginStartDao type
type MockGenerationCheckBeginStartDao struct {
	mock.Mock
}

type MockGenerationCheckBeginStartDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckBeginStartDao) EXPECT() *MockGenerationCheckBeginStartDao_Expecter {
	return &MockGenerationCheckBeginStartDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCheckBeginStartDao
func (_mock *MockGenerationCheckBeginStartDao) Exec(ctx context.Context, request *dao.GenerationBeginStartRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationBeginStartRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationBeginStartRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationBeginStartRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCheckBeginStartDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCheckBeginStartDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationBeginStartRequest
func (_e *MockGenerationCheckBeginStartDao_Expecter) Exec(ctx any, request any) *MockGenerationCheckBeginStartDao_Exec_Call {
	return &MockGenerationCheckBeginStartDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCheckBeginStartDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationBeginStartRequest)) *MockGenerationCheckBeginStartDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationBeginStartRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationBeginStartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCheckBeginStartDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCheckBeginStartDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCheckBeginStartDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationBeginStartRequest) (*dao.Generation, error)) *MockGenerationCheckBeginStartDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCheckReleaseStartDao creates a new instance of MockGenerationCheckReleaseStartDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckReleaseStartDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckReleaseStartDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckReleaseStartDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckReleaseStartDao is an autogenerated mock type for the GenerationCheckReleaseStartDao type
type MockGenerationCheckReleaseStartDao struct {
	mock.Mock
}

type MockGenerationCheckReleaseStartDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckReleaseStartDao) EXPECT() *MockGenerationCheckReleaseStartDao_Expecter {
	return &MockGenerationCheckReleaseStartDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCheckReleaseStartDao
func (_mock *MockGenerationCheckReleaseStartDao) Exec(ctx context.Context, request *dao.GenerationReleaseStartRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationReleaseStartRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationReleaseStartRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationReleaseStartRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCheckReleaseStartDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCheckReleaseStartDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationReleaseStartRequest
func (_e *MockGenerationCheckReleaseStartDao_Expecter) Exec(ctx any, request any) *MockGenerationCheckReleaseStartDao_Exec_Call {
	return &MockGenerationCheckReleaseStartDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCheckReleaseStartDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationReleaseStartRequest)) *MockGenerationCheckReleaseStartDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationReleaseStartRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationReleaseStartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCheckReleaseStartDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCheckReleaseStartDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCheckReleaseStartDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationReleaseStartRequest) (*dao.Generation, error)) *MockGenerationCheckReleaseStartDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCheckRecordProviderCallDao creates a new instance of MockGenerationCheckRecordProviderCallDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckRecordProviderCallDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckRecordProviderCallDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckRecordProviderCallDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckRecordProviderCallDao is an autogenerated mock type for the GenerationCheckRecordProviderCallDao type
type MockGenerationCheckRecordProviderCallDao struct {
	mock.Mock
}

type MockGenerationCheckRecordProviderCallDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckRecordProviderCallDao) EXPECT() *MockGenerationCheckRecordProviderCallDao_Expecter {
	return &MockGenerationCheckRecordProviderCallDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCheckRecordProviderCallDao
func (_mock *MockGenerationCheckRecordProviderCallDao) Exec(ctx context.Context, request *dao.GenerationRecordProviderCallRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRecordProviderCallRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRecordProviderCallRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationRecordProviderCallRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCheckRecordProviderCallDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCheckRecordProviderCallDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationRecordProviderCallRequest
func (_e *MockGenerationCheckRecordProviderCallDao_Expecter) Exec(ctx any, request any) *MockGenerationCheckRecordProviderCallDao_Exec_Call {
	return &MockGenerationCheckRecordProviderCallDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCheckRecordProviderCallDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationRecordProviderCallRequest)) *MockGenerationCheckRecordProviderCallDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationRecordProviderCallRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationRecordProviderCallRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCheckRecordProviderCallDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCheckRecordProviderCallDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCheckRecordProviderCallDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationRecordProviderCallRequest) (*dao.Generation, error)) *MockGenerationCheckRecordProviderCallDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCheckSettleDao creates a new instance of MockGenerationCheckSettleDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckSettleDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckSettleDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckSettleDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckSettleDao is an autogenerated mock type for the GenerationCheckSettleDao type
type MockGenerationCheckSettleDao struct {
	mock.Mock
}

type MockGenerationCheckSettleDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckSettleDao) EXPECT() *MockGenerationCheckSettleDao_Expecter {
	return &MockGenerationCheckSettleDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCheckSettleDao
func (_mock *MockGenerationCheckSettleDao) Exec(ctx context.Context, request *dao.GenerationSettleRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSettleRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSettleRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationSettleRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCheckSettleDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCheckSettleDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationSettleRequest
func (_e *MockGenerationCheckSettleDao_Expecter) Exec(ctx any, request any) *MockGenerationCheckSettleDao_Exec_Call {
	return &MockGenerationCheckSettleDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCheckSettleDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationSettleRequest)) *MockGenerationCheckSettleDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationSettleRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationSettleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCheckSettleDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCheckSettleDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCheckSettleDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationSettleRequest) (*dao.Generation, error)) *MockGenerationCheckSettleDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCheckRestartDao creates a new instance of MockGenerationCheckRestartDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckRestartDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckRestartDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckRestartDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckRestartDao is an autogenerated mock type for the GenerationCheckRestartDao type
type MockGenerationCheckRestartDao struct {
	mock.Mock
}

type MockGenerationCheckRestartDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckRestartDao) EXPECT() *MockGenerationCheckRestartDao_Expecter {
	return &MockGenerationCheckRestartDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCheckRestartDao
func (_mock *MockGenerationCheckRestartDao) Exec(ctx context.Context, request *dao.GenerationRestartRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRestartRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRestartRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationRestartRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCheckRestartDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCheckRestartDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationRestartRequest
func (_e *MockGenerationCheckRestartDao_Expecter) Exec(ctx any, request any) *MockGenerationCheckRestartDao_Exec_Call {
	return &MockGenerationCheckRestartDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCheckRestartDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationRestartRequest)) *MockGenerationCheckRestartDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationRestartRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationRestartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCheckRestartDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCheckRestartDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCheckRestartDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationRestartRequest) (*dao.Generation, error)) *MockGenerationCheckRestartDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCheckRequeueDao creates a new instance of MockGenerationCheckRequeueDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckRequeueDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckRequeueDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckRequeueDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckRequeueDao is an autogenerated mock type for the GenerationCheckRequeueDao type
type MockGenerationCheckRequeueDao struct {
	mock.Mock
}

type MockGenerationCheckRequeueDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckRequeueDao) EXPECT() *MockGenerationCheckRequeueDao_Expecter {
	return &MockGenerationCheckRequeueDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCheckRequeueDao
func (_mock *MockGenerationCheckRequeueDao) Exec(ctx context.Context, request *dao.GenerationRequeueRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRequeueRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRequeueRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationRequeueRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCheckRequeueDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCheckRequeueDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationRequeueRequest
func (_e *MockGenerationCheckRequeueDao_Expecter) Exec(ctx any, request any) *MockGenerationCheckRequeueDao_Exec_Call {
	return &MockGenerationCheckRequeueDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCheckRequeueDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationRequeueRequest)) *MockGenerationCheckRequeueDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationRequeueRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationRequeueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCheckRequeueDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCheckRequeueDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCheckRequeueDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationRequeueRequest) (*dao.Generation, error)) *MockGenerationCheckRequeueDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCheckUsageInsertDao creates a new instance of MockGenerationCheckUsageInsertDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckUsageInsertDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckUsageInsertDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckUsageInsertDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckUsageInsertDao is an autogenerated mock type for the GenerationCheckUsageInsertDao type
type MockGenerationCheckUsageInsertDao struct {
	mock.Mock
}

type MockGenerationCheckUsageInsertDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckUsageInsertDao) EXPECT() *MockGenerationCheckUsageInsertDao_Expecter {
	return &MockGenerationCheckUsageInsertDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCheckUsageInsertDao
func (_mock *MockGenerationCheckUsageInsertDao) Exec(ctx context.Context, request *dao.GenerationUsageInsertRequest) (*dao.GenerationUsage, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.GenerationUsage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageInsertRequest) (*dao.GenerationUsage, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageInsertRequest) *dao.GenerationUsage); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.GenerationUsage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationUsageInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCheckUsageInsertDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCheckUsageInsertDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationUsageInsertRequest
func (_e *MockGenerationCheckUsageInsertDao_Expecter) Exec(ctx any, request any) *MockGenerationCheckUsageInsertDao_Exec_Call {
	return &MockGenerationCheckUsageInsertDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCheckUsageInsertDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationUsageInsertRequest)) *MockGenerationCheckUsageInsertDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationUsageInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationUsageInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCheckUsageInsertDao_Exec_Call) Return(generationUsage *dao.GenerationUsage, err error) *MockGenerationCheckUsageInsertDao_Exec_Call {
	_c.Call.Return(generationUsage, err)
	return _c
}

func (_c *MockGenerationCheckUsageInsertDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationUsageInsertRequest) (*dao.GenerationUsage, error)) *MockGenerationCheckUsageInsertDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationCheckGetDao creates a new instance of MockGenerationCheckGetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCheckGetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCheckGetDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationCheckGetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationCheckGetDao is an autogenerated mock type for the GenerationCheckGetDao type
type MockGenerationCheckGetDao struct {
	mock.Mock
}

type MockGenerationCheckGetDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCheckGetDao) EXPECT() *MockGenerationCheckGetDao_Expecter {
	return &MockGenerationCheckGetDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCheckGetDao
func (_mock *MockGenerationCheckGetDao) Exec(ctx context.Context, request *dao.GenerationGetRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationGetRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationGetRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCheckGetDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCheckGetDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationGetRequest
func (_e *MockGenerationCheckGetDao_Expecter) Exec(ctx any, request any) *MockGenerationCheckGetDao_Exec_Call {
	return &MockGenerationCheckGetDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCheckGetDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationGetRequest)) *MockGenerationCheckGetDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationGetRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCheckGetDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCheckGetDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCheckGetDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationGetRequest) (*dao.Generation, error)) *MockGenerationCheckGetDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationGetDao creates a new instance of MockGenerationGetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationGetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationGetDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationGetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationGetDao is an autogenerated mock type for the GenerationGetDao type
type MockGenerationGetDao struct {
	mock.Mock
}

type MockGenerationGetDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationGetDao) EXPECT() *MockGenerationGetDao_Expecter {
	return &MockGenerationGetDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationGetDao
func (_mock *MockGenerationGetDao) Exec(ctx context.Context, request *dao.GenerationGetRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationGetRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationGetRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationGetDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationGetDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationGetRequest
func (_e *MockGenerationGetDao_Expecter) Exec(ctx any, request any) *MockGenerationGetDao_Exec_Call {
	return &MockGenerationGetDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationGetDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationGetRequest)) *MockGenerationGetDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationGetRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationGetDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationGetDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationGetDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationGetRequest) (*dao.Generation, error)) *MockGenerationGetDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationGetElectCheckDao creates a new instance of MockGenerationGetElectCheckDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationGetElectCheckDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationGetElectCheckDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationGetElectCheckDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationGetElectCheckDao is an autogenerated mock type for the GenerationGetElectCheckDao type
type MockGenerationGetElectCheckDao struct {
	mock.Mock
}

type MockGenerationGetElectCheckDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationGetElectCheckDao) EXPECT() *MockGenerationGetElectCheckDao_Expecter {
	return &MockGenerationGetElectCheckDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationGetElectCheckDao
func (_mock *MockGenerationGetElectCheckDao) Exec(ctx context.Context, request *dao.GenerationElectCheckRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationElectCheckRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationElectCheckRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationElectCheckRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationGetElectCheckDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationGetElectCheckDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationElectCheckRequest
func (_e *MockGenerationGetElectCheckDao_Expecter) Exec(ctx any, request any) *MockGenerationGetElectCheckDao_Exec_Call {
	return &MockGenerationGetElectCheckDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationGetElectCheckDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationElectCheckRequest)) *MockGenerationGetElectCheckDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationElectCheckRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationElectCheckRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationGetElectCheckDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationGetElectCheckDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationGetElectCheckDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationElectCheckRequest) (*dao.Generation, error)) *MockGenerationGetElectCheckDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationGetUsageListDao creates a new instance of MockGenerationGetUsageListDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationGetUsageListDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationGetUsageListDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationGetUsageListDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationGetUsageListDao is an autogenerated mock type for the GenerationGetUsageListDao type
type MockGenerationGetUsageListDao struct {
	mock.Mock
}

type MockGenerationGetUsageListDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationGetUsageListDao) EXPECT() *MockGenerationGetUsageListDao_Expecter {
	return &MockGenerationGetUsageListDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationGetUsageListDao
func (_mock *MockGenerationGetUsageListDao) Exec(ctx context.Context, request *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.GenerationUsage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageListRequest) []*dao.GenerationUsage); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.GenerationUsage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationUsageListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationGetUsageListDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationGetUsageListDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationUsageListRequest
func (_e *MockGenerationGetUsageListDao_Expecter) Exec(ctx any, request any) *MockGenerationGetUsageListDao_Exec_Call {
	return &MockGenerationGetUsageListDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationGetUsageListDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationUsageListRequest)) *MockGenerationGetUsageListDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationUsageListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationUsageListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationGetUsageListDao_Exec_Call) Return(generationUsages []*dao.GenerationUsage, err error) *MockGenerationGetUsageListDao_Exec_Call {
	_c.Call.Return(generationUsages, err)
	return _c
}

func (_c *MockGenerationGetUsageListDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error)) *MockGenerationGetUsageListDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationGetServiceCheck creates a new instance of MockGenerationGetServiceCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationGetServiceCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationGetServiceCheck {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationGetServiceCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationGetServiceCheck is an autogenerated mock type for the GenerationGetServiceCheck type
type MockGenerationGetServiceCheck struct {
	mock.Mock
}

type MockGenerationGetServiceCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationGetServiceCheck) EXPECT() *MockGenerationGetServiceCheck_Expecter {
	return &MockGenerationGetServiceCheck_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationGetServiceCheck
func (_mock *MockGenerationGetServiceCheck) Exec(ctx context.Context, request *core.GenerationCheckRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCheckRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCheckRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationCheckRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationGetServiceCheck_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationGetServiceCheck_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationCheckRequest
func (_e *MockGenerationGetServiceCheck_Expecter) Exec(ctx any, request any) *MockGenerationGetServiceCheck_Exec_Call {
	return &MockGenerationGetServiceCheck_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationGetServiceCheck_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationCheckRequest)) *MockGenerationGetServiceCheck_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationCheckRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationCheckRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationGetServiceCheck_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationGetServiceCheck_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationGetServiceCheck_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationCheckRequest) (*dao.Generation, error)) *MockGenerationGetServiceCheck_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationSubmitDao creates a new instance of MockGenerationSubmitDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationSubmitDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationSubmitDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationSubmitDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationSubmitDao is an autogenerated mock type for the GenerationSubmitDao type
type MockGenerationSubmitDao struct {
	mock.Mock
}

type MockGenerationSubmitDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationSubmitDao) EXPECT() *MockGenerationSubmitDao_Expecter {
	return &MockGenerationSubmitDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationSubmitDao
func (_mock *MockGenerationSubmitDao) Exec(ctx context.Context, request *dao.GenerationSubmitRequest) (*dao.GenerationSubmitResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.GenerationSubmitResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSubmitRequest) (*dao.GenerationSubmitResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSubmitRequest) *dao.GenerationSubmitResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.GenerationSubmitResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationSubmitRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationSubmitDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationSubmitDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationSubmitRequest
func (_e *MockGenerationSubmitDao_Expecter) Exec(ctx any, request any) *MockGenerationSubmitDao_Exec_Call {
	return &MockGenerationSubmitDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationSubmitDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationSubmitRequest)) *MockGenerationSubmitDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationSubmitRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationSubmitRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationSubmitDao_Exec_Call) Return(generationSubmitResult *dao.GenerationSubmitResult, err error) *MockGenerationSubmitDao_Exec_Call {
	_c.Call.Return(generationSubmitResult, err)
	return _c
}

func (_c *MockGenerationSubmitDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationSubmitRequest) (*dao.GenerationSubmitResult, error)) *MockGenerationSubmitDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationSubmitUsageListDao creates a new instance of MockGenerationSubmitUsageListDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationSubmitUsageListDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationSubmitUsageListDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationSubmitUsageListDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationSubmitUsageListDao is an autogenerated mock type for the GenerationSubmitUsageListDao type
type MockGenerationSubmitUsageListDao struct {
	mock.Mock
}

type MockGenerationSubmitUsageListDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationSubmitUsageListDao) EXPECT() *MockGenerationSubmitUsageListDao_Expecter {
	return &MockGenerationSubmitUsageListDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationSubmitUsageListDao
func (_mock *MockGenerationSubmitUsageListDao) Exec(ctx context.Context, request *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.GenerationUsage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageListRequest) []*dao.GenerationUsage); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.GenerationUsage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationUsageListRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationSubmitUsageListDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationSubmitUsageListDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationUsageListRequest
func (_e *MockGenerationSubmitUsageListDao_Expecter) Exec(ctx any, request any) *MockGenerationSubmitUsageListDao_Exec_Call {
	return &MockGenerationSubmitUsageListDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationSubmitUsageListDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationUsageListRequest)) *MockGenerationSubmitUsageListDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationUsageListRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationUsageListRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationSubmitUsageListDao_Exec_Call) Return(generationUsages []*dao.GenerationUsage, err error) *MockGenerationSubmitUsageListDao_Exec_Call {
	_c.Call.Return(generationUsages, err)
	return _c
}

func (_c *MockGenerationSubmitUsageListDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationUsageListRequest) ([]*dao.GenerationUsage, error)) *MockGenerationSubmitUsageListDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationSubmitServiceCheck creates a new instance of MockGenerationSubmitServiceCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationSubmitServiceCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationSubmitServiceCheck {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationSubmitServiceCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationSubmitServiceCheck is an autogenerated mock type for the GenerationSubmitServiceCheck type
type MockGenerationSubmitServiceCheck struct {
	mock.Mock
}

type MockGenerationSubmitServiceCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationSubmitServiceCheck) EXPECT() *MockGenerationSubmitServiceCheck_Expecter {
	return &MockGenerationSubmitServiceCheck_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationSubmitServiceCheck
func (_mock *MockGenerationSubmitServiceCheck) Exec(ctx context.Context, request *core.GenerationCheckRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCheckRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCheckRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationCheckRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationSubmitServiceCheck_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationSubmitServiceCheck_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationCheckRequest
func (_e *MockGenerationSubmitServiceCheck_Expecter) Exec(ctx any, request any) *MockGenerationSubmitServiceCheck_Exec_Call {
	return &MockGenerationSubmitServiceCheck_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationSubmitServiceCheck_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationCheckRequest)) *MockGenerationSubmitServiceCheck_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationCheckRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationCheckRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationSubmitServiceCheck_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationSubmitServiceCheck_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationSubmitServiceCheck_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationCheckRequest) (*dao.Generation, error)) *MockGenerationSubmitServiceCheck_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationSweepDao creates a new instance of MockGenerationSweepDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationSweepDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationSweepDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationSweepDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationSweepDao is an autogenerated mock type for the GenerationSweepDao type
type MockGenerationSweepDao struct {
	mock.Mock
}

type MockGenerationSweepDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationSweepDao) EXPECT() *MockGenerationSweepDao_Expecter {
	return &MockGenerationSweepDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationSweepDao
func (_mock *MockGenerationSweepDao) Exec(ctx context.Context, request *dao.GenerationSweepRequest) ([]*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSweepRequest) ([]*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSweepRequest) []*dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationSweepRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationSweepDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationSweepDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationSweepRequest
func (_e *MockGenerationSweepDao_Expecter) Exec(ctx any, request any) *MockGenerationSweepDao_Exec_Call {
	return &MockGenerationSweepDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationSweepDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationSweepRequest)) *MockGenerationSweepDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationSweepRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationSweepRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationSweepDao_Exec_Call) Return(generations []*dao.Generation, err error) *MockGenerationSweepDao_Exec_Call {
	_c.Call.Return(generations, err)
	return _c
}

func (_c *MockGenerationSweepDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationSweepRequest) ([]*dao.Generation, error)) *MockGenerationSweepDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationSweepServiceCheck creates a new instance of MockGenerationSweepServiceCheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationSweepServiceCheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationSweepServiceCheck {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockGenerationSweepServiceCheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockGenerationSweepServiceCheck is an autogenerated mock type for the GenerationSweepServiceCheck type
type MockGenerationSweepServiceCheck struct {
	mock.Mock
}

type MockGenerationSweepServiceCheck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationSweepServiceCheck) EXPECT() *MockGenerationSweepServiceCheck_Expecter {
	return &MockGenerationSweepServiceCheck_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationSweepServiceCheck
func (_mock *MockGenerationSweepServiceCheck) Exec(ctx context.Context, request *core.GenerationCheckRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCheckRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCheckRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationCheckRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationSweepServiceCheck_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationSweepServiceCheck_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationCheckRequest
func (_e *MockGenerationSweepServiceCheck_Expecter) Exec(ctx any, request any) *MockGenerationSweepServiceCheck_Exec_Call {
	return &MockGenerationSweepServiceCheck_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationSweepServiceCheck_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationCheckRequest)) *MockGenerationSweepServiceCheck_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationCheckRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationCheckRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationSweepServiceCheck_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationSweepServiceCheck_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationSweepServiceCheck_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationCheckRequest) (*dao.Generation, error)) *MockGenerationSweepServiceCheck_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueDepthDao creates a new instance of MockQueueDepthDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueDepthDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueDepthDao {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockQueueDepthDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockQueueDepthDao is an autogenerated mock type for the QueueDepthDao type
type MockQueueDepthDao struct {
	mock.Mock
}

type MockQueueDepthDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueDepthDao) EXPECT() *MockQueueDepthDao_Expecter {
	return &MockQueueDepthDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockQueueDepthDao
func (_mock *MockQueueDepthDao) Exec(ctx context.Context) (*dao.GenerationQueueDepth, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.GenerationQueueDepth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*dao.GenerationQueueDepth, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *dao.GenerationQueueDepth); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.GenerationQueueDepth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueDepthDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockQueueDepthDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueueDepthDao_Expecter) Exec(ctx any) *MockQueueDepthDao_Exec_Call {
	return &MockQueueDepthDao_Exec_Call{Call: _e.mock.On("Exec", ctx)}
}

func (_c *MockQueueDepthDao_Exec_Call) Run(run func(ctx context.Context)) *MockQueueDepthDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueueDepthDao_Exec_Call) Return(generationQueueDepth *dao.GenerationQueueDepth, err error) *MockQueueDepthDao_Exec_Call {
	_c.Call.Return(generationQueueDepth, err)
	return _c
}

func (_c *MockQueueDepthDao_Exec_Call) RunAndReturn(run func(ctx context.Context) (*dao.GenerationQueueDepth, error)) *MockQueueDepthDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}
