// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package coremocks

import (
	"context"

	"github.com/a-novel/service-genai/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGenerationCancelDao creates a new instance of MockGenerationCancelDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationCancelDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationCancelDao {
	mock := &MockGenerationCancelDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerationCancelDao is an autogenerated mock type for the GenerationCancelDao type
type MockGenerationCancelDao struct {
	mock.Mock
}

type MockGenerationCancelDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationCancelDao) EXPECT() *MockGenerationCancelDao_Expecter {
	return &MockGenerationCancelDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationCancelDao
func (_mock *MockGenerationCancelDao) Exec(ctx context.Context, request *dao.GenerationRequestCancelRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRequestCancelRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRequestCancelRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationRequestCancelRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationCancelDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationCancelDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationRequestCancelRequest
func (_e *MockGenerationCancelDao_Expecter) Exec(ctx any, request any) *MockGenerationCancelDao_Exec_Call {
	return &MockGenerationCancelDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationCancelDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationRequestCancelRequest)) *MockGenerationCancelDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationRequestCancelRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationRequestCancelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationCancelDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationCancelDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationCancelDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationRequestCancelRequest) (*dao.Generation, error)) *MockGenerationCancelDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationGetDao creates a new instance of MockGenerationGetDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationGetDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationGetDao {
	mock := &MockGenerationGetDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerationGetDao is an autogenerated mock type for the GenerationGetDao type
type MockGenerationGetDao struct {
	mock.Mock
}

type MockGenerationGetDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationGetDao) EXPECT() *MockGenerationGetDao_Expecter {
	return &MockGenerationGetDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationGetDao
func (_mock *MockGenerationGetDao) Exec(ctx context.Context, request *dao.GenerationGetRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationGetRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationGetRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationGetDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationGetDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationGetRequest
func (_e *MockGenerationGetDao_Expecter) Exec(ctx any, request any) *MockGenerationGetDao_Exec_Call {
	return &MockGenerationGetDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationGetDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationGetRequest)) *MockGenerationGetDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationGetRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationGetDao_Exec_Call) Return(generation *dao.Generation, err error) *MockGenerationGetDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGenerationGetDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationGetRequest) (*dao.Generation, error)) *MockGenerationGetDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGenerationSubmitDao creates a new instance of MockGenerationSubmitDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGenerationSubmitDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGenerationSubmitDao {
	mock := &MockGenerationSubmitDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGenerationSubmitDao is an autogenerated mock type for the GenerationSubmitDao type
type MockGenerationSubmitDao struct {
	mock.Mock
}

type MockGenerationSubmitDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGenerationSubmitDao) EXPECT() *MockGenerationSubmitDao_Expecter {
	return &MockGenerationSubmitDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGenerationSubmitDao
func (_mock *MockGenerationSubmitDao) Exec(ctx context.Context, request *dao.GenerationSubmitRequest) (*dao.GenerationSubmitResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.GenerationSubmitResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSubmitRequest) (*dao.GenerationSubmitResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSubmitRequest) *dao.GenerationSubmitResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.GenerationSubmitResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationSubmitRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGenerationSubmitDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGenerationSubmitDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationSubmitRequest
func (_e *MockGenerationSubmitDao_Expecter) Exec(ctx any, request any) *MockGenerationSubmitDao_Exec_Call {
	return &MockGenerationSubmitDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGenerationSubmitDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationSubmitRequest)) *MockGenerationSubmitDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationSubmitRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationSubmitRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGenerationSubmitDao_Exec_Call) Return(generationSubmitResult *dao.GenerationSubmitResult, err error) *MockGenerationSubmitDao_Exec_Call {
	_c.Call.Return(generationSubmitResult, err)
	return _c
}

func (_c *MockGenerationSubmitDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationSubmitRequest) (*dao.GenerationSubmitResult, error)) *MockGenerationSubmitDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueDepthDao creates a new instance of MockQueueDepthDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueDepthDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueDepthDao {
	mock := &MockQueueDepthDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueDepthDao is an autogenerated mock type for the QueueDepthDao type
type MockQueueDepthDao struct {
	mock.Mock
}

type MockQueueDepthDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueDepthDao) EXPECT() *MockQueueDepthDao_Expecter {
	return &MockQueueDepthDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockQueueDepthDao
func (_mock *MockQueueDepthDao) Exec(ctx context.Context) (*dao.GenerationQueueDepth, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.GenerationQueueDepth
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*dao.GenerationQueueDepth, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *dao.GenerationQueueDepth); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.GenerationQueueDepth)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueDepthDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockQueueDepthDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueueDepthDao_Expecter) Exec(ctx any) *MockQueueDepthDao_Exec_Call {
	return &MockQueueDepthDao_Exec_Call{Call: _e.mock.On("Exec", ctx)}
}

func (_c *MockQueueDepthDao_Exec_Call) Run(run func(ctx context.Context)) *MockQueueDepthDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueueDepthDao_Exec_Call) Return(generationQueueDepth *dao.GenerationQueueDepth, err error) *MockQueueDepthDao_Exec_Call {
	_c.Call.Return(generationQueueDepth, err)
	return _c
}

func (_c *MockQueueDepthDao_Exec_Call) RunAndReturn(run func(ctx context.Context) (*dao.GenerationQueueDepth, error)) *MockQueueDepthDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReaperDao creates a new instance of MockReaperDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReaperDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReaperDao {
	mock := &MockReaperDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReaperDao is an autogenerated mock type for the ReaperDao type
type MockReaperDao struct {
	mock.Mock
}

type MockReaperDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReaperDao) EXPECT() *MockReaperDao_Expecter {
	return &MockReaperDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockReaperDao
func (_mock *MockReaperDao) Exec(ctx context.Context, request *dao.GenerationReapRequest) ([]*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationReapRequest) ([]*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationReapRequest) []*dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationReapRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReaperDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockReaperDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationReapRequest
func (_e *MockReaperDao_Expecter) Exec(ctx any, request any) *MockReaperDao_Exec_Call {
	return &MockReaperDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockReaperDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationReapRequest)) *MockReaperDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationReapRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationReapRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReaperDao_Exec_Call) Return(generations []*dao.Generation, err error) *MockReaperDao_Exec_Call {
	_c.Call.Return(generations, err)
	return _c
}

func (_c *MockReaperDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationReapRequest) ([]*dao.Generation, error)) *MockReaperDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUsageQueryDao creates a new instance of MockUsageQueryDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUsageQueryDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUsageQueryDao {
	mock := &MockUsageQueryDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUsageQueryDao is an autogenerated mock type for the UsageQueryDao type
type MockUsageQueryDao struct {
	mock.Mock
}

type MockUsageQueryDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUsageQueryDao) EXPECT() *MockUsageQueryDao_Expecter {
	return &MockUsageQueryDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockUsageQueryDao
func (_mock *MockUsageQueryDao) Exec(ctx context.Context, request *dao.GenerationUsageQueryRequest) ([]*dao.GenerationUsageGroup, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.GenerationUsageGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageQueryRequest) ([]*dao.GenerationUsageGroup, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageQueryRequest) []*dao.GenerationUsageGroup); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.GenerationUsageGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationUsageQueryRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUsageQueryDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockUsageQueryDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationUsageQueryRequest
func (_e *MockUsageQueryDao_Expecter) Exec(ctx any, request any) *MockUsageQueryDao_Exec_Call {
	return &MockUsageQueryDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockUsageQueryDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationUsageQueryRequest)) *MockUsageQueryDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationUsageQueryRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationUsageQueryRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUsageQueryDao_Exec_Call) Return(generationUsageGroups []*dao.GenerationUsageGroup, err error) *MockUsageQueryDao_Exec_Call {
	_c.Call.Return(generationUsageGroups, err)
	return _c
}

func (_c *MockUsageQueryDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationUsageQueryRequest) ([]*dao.GenerationUsageGroup, error)) *MockUsageQueryDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkerClaimDao creates a new instance of MockWorkerClaimDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerClaimDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerClaimDao {
	mock := &MockWorkerClaimDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkerClaimDao is an autogenerated mock type for the WorkerClaimDao type
type MockWorkerClaimDao struct {
	mock.Mock
}

type MockWorkerClaimDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerClaimDao) EXPECT() *MockWorkerClaimDao_Expecter {
	return &MockWorkerClaimDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockWorkerClaimDao
func (_mock *MockWorkerClaimDao) Exec(ctx context.Context, request *dao.GenerationClaimRequest) ([]*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationClaimRequest) ([]*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationClaimRequest) []*dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationClaimRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkerClaimDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockWorkerClaimDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationClaimRequest
func (_e *MockWorkerClaimDao_Expecter) Exec(ctx any, request any) *MockWorkerClaimDao_Exec_Call {
	return &MockWorkerClaimDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockWorkerClaimDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationClaimRequest)) *MockWorkerClaimDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationClaimRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationClaimRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkerClaimDao_Exec_Call) Return(generations []*dao.Generation, err error) *MockWorkerClaimDao_Exec_Call {
	_c.Call.Return(generations, err)
	return _c
}

func (_c *MockWorkerClaimDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationClaimRequest) ([]*dao.Generation, error)) *MockWorkerClaimDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkerRecordProviderCallDao creates a new instance of MockWorkerRecordProviderCallDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerRecordProviderCallDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerRecordProviderCallDao {
	mock := &MockWorkerRecordProviderCallDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkerRecordProviderCallDao is an autogenerated mock type for the WorkerRecordProviderCallDao type
type MockWorkerRecordProviderCallDao struct {
	mock.Mock
}

type MockWorkerRecordProviderCallDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerRecordProviderCallDao) EXPECT() *MockWorkerRecordProviderCallDao_Expecter {
	return &MockWorkerRecordProviderCallDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockWorkerRecordProviderCallDao
func (_mock *MockWorkerRecordProviderCallDao) Exec(ctx context.Context, request *dao.GenerationRecordProviderCallRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRecordProviderCallRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRecordProviderCallRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationRecordProviderCallRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkerRecordProviderCallDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockWorkerRecordProviderCallDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationRecordProviderCallRequest
func (_e *MockWorkerRecordProviderCallDao_Expecter) Exec(ctx any, request any) *MockWorkerRecordProviderCallDao_Exec_Call {
	return &MockWorkerRecordProviderCallDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockWorkerRecordProviderCallDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationRecordProviderCallRequest)) *MockWorkerRecordProviderCallDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationRecordProviderCallRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationRecordProviderCallRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkerRecordProviderCallDao_Exec_Call) Return(generation *dao.Generation, err error) *MockWorkerRecordProviderCallDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockWorkerRecordProviderCallDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationRecordProviderCallRequest) (*dao.Generation, error)) *MockWorkerRecordProviderCallDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkerSettleDao creates a new instance of MockWorkerSettleDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerSettleDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerSettleDao {
	mock := &MockWorkerSettleDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkerSettleDao is an autogenerated mock type for the WorkerSettleDao type
type MockWorkerSettleDao struct {
	mock.Mock
}

type MockWorkerSettleDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerSettleDao) EXPECT() *MockWorkerSettleDao_Expecter {
	return &MockWorkerSettleDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockWorkerSettleDao
func (_mock *MockWorkerSettleDao) Exec(ctx context.Context, request *dao.GenerationSettleRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSettleRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationSettleRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationSettleRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkerSettleDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockWorkerSettleDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationSettleRequest
func (_e *MockWorkerSettleDao_Expecter) Exec(ctx any, request any) *MockWorkerSettleDao_Exec_Call {
	return &MockWorkerSettleDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockWorkerSettleDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationSettleRequest)) *MockWorkerSettleDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationSettleRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationSettleRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkerSettleDao_Exec_Call) Return(generation *dao.Generation, err error) *MockWorkerSettleDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockWorkerSettleDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationSettleRequest) (*dao.Generation, error)) *MockWorkerSettleDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkerRequeueDao creates a new instance of MockWorkerRequeueDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerRequeueDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerRequeueDao {
	mock := &MockWorkerRequeueDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkerRequeueDao is an autogenerated mock type for the WorkerRequeueDao type
type MockWorkerRequeueDao struct {
	mock.Mock
}

type MockWorkerRequeueDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerRequeueDao) EXPECT() *MockWorkerRequeueDao_Expecter {
	return &MockWorkerRequeueDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockWorkerRequeueDao
func (_mock *MockWorkerRequeueDao) Exec(ctx context.Context, request *dao.GenerationRequeueRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRequeueRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationRequeueRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationRequeueRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkerRequeueDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockWorkerRequeueDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationRequeueRequest
func (_e *MockWorkerRequeueDao_Expecter) Exec(ctx any, request any) *MockWorkerRequeueDao_Exec_Call {
	return &MockWorkerRequeueDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockWorkerRequeueDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationRequeueRequest)) *MockWorkerRequeueDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationRequeueRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationRequeueRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkerRequeueDao_Exec_Call) Return(generation *dao.Generation, err error) *MockWorkerRequeueDao_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockWorkerRequeueDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationRequeueRequest) (*dao.Generation, error)) *MockWorkerRequeueDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWorkerUsageInsertDao creates a new instance of MockWorkerUsageInsertDao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkerUsageInsertDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkerUsageInsertDao {
	mock := &MockWorkerUsageInsertDao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkerUsageInsertDao is an autogenerated mock type for the WorkerUsageInsertDao type
type MockWorkerUsageInsertDao struct {
	mock.Mock
}

type MockWorkerUsageInsertDao_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkerUsageInsertDao) EXPECT() *MockWorkerUsageInsertDao_Expecter {
	return &MockWorkerUsageInsertDao_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockWorkerUsageInsertDao
func (_mock *MockWorkerUsageInsertDao) Exec(ctx context.Context, request *dao.GenerationUsageInsertRequest) (*dao.GenerationUsage, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.GenerationUsage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageInsertRequest) (*dao.GenerationUsage, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dao.GenerationUsageInsertRequest) *dao.GenerationUsage); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.GenerationUsage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dao.GenerationUsageInsertRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkerUsageInsertDao_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockWorkerUsageInsertDao_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.GenerationUsageInsertRequest
func (_e *MockWorkerUsageInsertDao_Expecter) Exec(ctx any, request any) *MockWorkerUsageInsertDao_Exec_Call {
	return &MockWorkerUsageInsertDao_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockWorkerUsageInsertDao_Exec_Call) Run(run func(ctx context.Context, request *dao.GenerationUsageInsertRequest)) *MockWorkerUsageInsertDao_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dao.GenerationUsageInsertRequest
		if args[1] != nil {
			arg1 = args[1].(*dao.GenerationUsageInsertRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkerUsageInsertDao_Exec_Call) Return(generationUsage *dao.GenerationUsage, err error) *MockWorkerUsageInsertDao_Exec_Call {
	_c.Call.Return(generationUsage, err)
	return _c
}

func (_c *MockWorkerUsageInsertDao_Exec_Call) RunAndReturn(run func(ctx context.Context, request *dao.GenerationUsageInsertRequest) (*dao.GenerationUsage, error)) *MockWorkerUsageInsertDao_Exec_Call {
	_c.Call.Return(run)
	return _c
}
