// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: anovel/genai/v1/generation_submit.proto

package genaiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenerationSubmitService_GenerationSubmit_FullMethodName = "/anovel.genai.v1.GenerationSubmitService/GenerationSubmit"
)

// GenerationSubmitServiceClient is the client API for GenerationSubmitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GenerationSubmitService records a generation for execution, deduplicating on the idempotency key.
type GenerationSubmitServiceClient interface {
	GenerationSubmit(ctx context.Context, in *GenerationSubmitRequest, opts ...grpc.CallOption) (*GenerationSubmitResponse, error)
}

type generationSubmitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerationSubmitServiceClient(cc grpc.ClientConnInterface) GenerationSubmitServiceClient {
	return &generationSubmitServiceClient{cc}
}

func (c *generationSubmitServiceClient) GenerationSubmit(ctx context.Context, in *GenerationSubmitRequest, opts ...grpc.CallOption) (*GenerationSubmitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationSubmitResponse)
	err := c.cc.Invoke(ctx, GenerationSubmitService_GenerationSubmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerationSubmitServiceServer is the server API for GenerationSubmitService service.
// All implementations must embed UnimplementedGenerationSubmitServiceServer
// for forward compatibility.
//
// GenerationSubmitService records a generation for execution, deduplicating on the idempotency key.
type GenerationSubmitServiceServer interface {
	GenerationSubmit(context.Context, *GenerationSubmitRequest) (*GenerationSubmitResponse, error)
	mustEmbedUnimplementedGenerationSubmitServiceServer()
}

// UnimplementedGenerationSubmitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerationSubmitServiceServer struct{}

func (UnimplementedGenerationSubmitServiceServer) GenerationSubmit(context.Context, *GenerationSubmitRequest) (*GenerationSubmitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerationSubmit not implemented")
}
func (UnimplementedGenerationSubmitServiceServer) mustEmbedUnimplementedGenerationSubmitServiceServer() {
}
func (UnimplementedGenerationSubmitServiceServer) testEmbeddedByValue() {}

// UnsafeGenerationSubmitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerationSubmitServiceServer will
// result in compilation errors.
type UnsafeGenerationSubmitServiceServer interface {
	mustEmbedUnimplementedGenerationSubmitServiceServer()
}

func RegisterGenerationSubmitServiceServer(s grpc.ServiceRegistrar, srv GenerationSubmitServiceServer) {
	// If the following call panics, it indicates UnimplementedGenerationSubmitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenerationSubmitService_ServiceDesc, srv)
}

func _GenerationSubmitService_GenerationSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerationSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerationSubmitServiceServer).GenerationSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenerationSubmitService_GenerationSubmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerationSubmitServiceServer).GenerationSubmit(ctx, req.(*GenerationSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenerationSubmitService_ServiceDesc is the grpc.ServiceDesc for GenerationSubmitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenerationSubmitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anovel.genai.v1.GenerationSubmitService",
	HandlerType: (*GenerationSubmitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerationSubmit",
			Handler:    _GenerationSubmitService_GenerationSubmit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anovel/genai/v1/generation_submit.proto",
}
