// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: anovel/genai/v1/generation.proto

package genaiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerationStatus is where a generation sits in its lifecycle.
type GenerationStatus int32

const (
	// GENERATION_STATUS_UNSPECIFIED means the status was not set. Never a value the service stores.
	GenerationStatus_GENERATION_STATUS_UNSPECIFIED GenerationStatus = 0
	// GENERATION_STATUS_PENDING means the generation is waiting to be picked up.
	GenerationStatus_GENERATION_STATUS_PENDING GenerationStatus = 1
	// GENERATION_STATUS_RUNNING means a worker holds a lease and is executing it.
	GenerationStatus_GENERATION_STATUS_RUNNING GenerationStatus = 2
	// GENERATION_STATUS_SUCCEEDED means the provider returned a usable output.
	GenerationStatus_GENERATION_STATUS_SUCCEEDED GenerationStatus = 3
	// GENERATION_STATUS_FAILED means the generation failed with no attempt left to retry.
	GenerationStatus_GENERATION_STATUS_FAILED GenerationStatus = 4
	// GENERATION_STATUS_ABANDONED means the lease expired with no attempt remaining — the worker
	// running it died mid-run.
	GenerationStatus_GENERATION_STATUS_ABANDONED GenerationStatus = 5
	// GENERATION_STATUS_CANCELLED means the generation was stopped on the owner's request.
	GenerationStatus_GENERATION_STATUS_CANCELLED GenerationStatus = 6
)

// Enum value maps for GenerationStatus.
var (
	GenerationStatus_name = map[int32]string{
		0: "GENERATION_STATUS_UNSPECIFIED",
		1: "GENERATION_STATUS_PENDING",
		2: "GENERATION_STATUS_RUNNING",
		3: "GENERATION_STATUS_SUCCEEDED",
		4: "GENERATION_STATUS_FAILED",
		5: "GENERATION_STATUS_ABANDONED",
		6: "GENERATION_STATUS_CANCELLED",
	}
	GenerationStatus_value = map[string]int32{
		"GENERATION_STATUS_UNSPECIFIED": 0,
		"GENERATION_STATUS_PENDING":     1,
		"GENERATION_STATUS_RUNNING":     2,
		"GENERATION_STATUS_SUCCEEDED":   3,
		"GENERATION_STATUS_FAILED":      4,
		"GENERATION_STATUS_ABANDONED":   5,
		"GENERATION_STATUS_CANCELLED":   6,
	}
)

func (x GenerationStatus) Enum() *GenerationStatus {
	p := new(GenerationStatus)
	*p = x
	return p
}

func (x GenerationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_anovel_genai_v1_generation_proto_enumTypes[0].Descriptor()
}

func (GenerationStatus) Type() protoreflect.EnumType {
	return &file_anovel_genai_v1_generation_proto_enumTypes[0]
}

func (x GenerationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerationStatus.Descriptor instead.
func (GenerationStatus) EnumDescriptor() ([]byte, []int) {
	return file_anovel_genai_v1_generation_proto_rawDescGZIP(), []int{0}
}

// A Generation is one AI generative call as this service records it.
//
// The service is a crash-safe metering proxy: the caller composes the provider request and owns
// every parameter in it, and this service executes it durably, never pays for it twice, and records
// what it consumed.
type Generation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// OwnerID is the user this acts for, formatted as a UUID. Supplied by the calling service.
	OwnerId string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// Purpose is the caller's own label for what this spend is attributed to. Opaque here.
	Purpose string `protobuf:"bytes,3,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// Status is where the generation sits in its lifecycle.
	Status GenerationStatus `protobuf:"varint,4,opt,name=status,proto3,enum=anovel.genai.v1.GenerationStatus" json:"status,omitempty"`
	// Attempt counts runs already begun.
	Attempt int32 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// MaxAttempts caps the value Attempt may reach.
	MaxAttempts int32 `protobuf:"varint,6,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	// Output is the provider's response on success, as JSON bytes. Empty until it succeeds.
	Output []byte `protobuf:"bytes,7,opt,name=output,proto3" json:"output,omitempty"`
	// Error is the serialised failure on a terminal failure. Empty otherwise.
	Error string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	// Creation timestamp, formatted as RFC 3339.
	CreatedAt string `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp of the most recent update, formatted as RFC 3339.
	UpdatedAt string `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Timestamp the generation reached a terminal status, formatted as RFC 3339. Empty until then.
	SettledAt string `protobuf:"bytes,11,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	// Timestamp the settled generation's content may be purged, formatted as RFC 3339. Its usage
	// record carries no content and is kept regardless.
	ExpiresAt     string `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generation) Reset() {
	*x = Generation{}
	mi := &file_anovel_genai_v1_generation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generation) ProtoMessage() {}

func (x *Generation) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v1_generation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generation.ProtoReflect.Descriptor instead.
func (*Generation) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v1_generation_proto_rawDescGZIP(), []int{0}
}

func (x *Generation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Generation) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Generation) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *Generation) GetStatus() GenerationStatus {
	if x != nil {
		return x.Status
	}
	return GenerationStatus_GENERATION_STATUS_UNSPECIFIED
}

func (x *Generation) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Generation) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *Generation) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Generation) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Generation) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Generation) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Generation) GetSettledAt() string {
	if x != nil {
		return x.SettledAt
	}
	return ""
}

func (x *Generation) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_anovel_genai_v1_generation_proto protoreflect.FileDescriptor

const file_anovel_genai_v1_generation_proto_rawDesc = "" +
	"\n" +
	" anovel/genai/v1/generation.proto\x12\x0fanovel.genai.v1\"\x8b\x03\n" +
	"\n" +
	"Generation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x18\n" +
	"\apurpose\x18\x03 \x01(\tR\apurpose\x129\n" +
	"\x06status\x18\x04 \x01(\x0e2!.anovel.genai.v1.GenerationStatusR\x06status\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\x06 \x01(\x05R\vmaxAttempts\x12\x16\n" +
	"\x06output\x18\a \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"settled_at\x18\v \x01(\tR\tsettledAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\f \x01(\tR\texpiresAtJ\x04\b\r\x10\x0eR\x10provider_call_id*\xf4\x01\n" +
	"\x10GenerationStatus\x12!\n" +
	"\x1dGENERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19GENERATION_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19GENERATION_STATUS_RUNNING\x10\x02\x12\x1f\n" +
	"\x1bGENERATION_STATUS_SUCCEEDED\x10\x03\x12\x1c\n" +
	"\x18GENERATION_STATUS_FAILED\x10\x04\x12\x1f\n" +
	"\x1bGENERATION_STATUS_ABANDONED\x10\x05\x12\x1f\n" +
	"\x1bGENERATION_STATUS_CANCELLED\x10\x06B\xd9\x01\n" +
	"\x13com.anovel.genai.v1B\x0fGenerationProtoP\x01ZSgithub.com/a-novel/service-genai/internal/handlers/protogen/anovel/genai/v1;genaiv1\xa2\x02\x03AGX\xaa\x02\x0fAnovel.Genai.V1\xca\x02\x0fAnovel\\Genai\\V1\xe2\x02\x1bAnovel\\Genai\\V1\\GPBMetadata\xea\x02\x11Anovel::Genai::V1b\x06proto3"

var (
	file_anovel_genai_v1_generation_proto_rawDescOnce sync.Once
	file_anovel_genai_v1_generation_proto_rawDescData []byte
)

func file_anovel_genai_v1_generation_proto_rawDescGZIP() []byte {
	file_anovel_genai_v1_generation_proto_rawDescOnce.Do(func() {
		file_anovel_genai_v1_generation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_genai_v1_generation_proto_rawDesc), len(file_anovel_genai_v1_generation_proto_rawDesc)))
	})
	return file_anovel_genai_v1_generation_proto_rawDescData
}

var file_anovel_genai_v1_generation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_anovel_genai_v1_generation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_anovel_genai_v1_generation_proto_goTypes = []any{
	(GenerationStatus)(0), // 0: anovel.genai.v1.GenerationStatus
	(*Generation)(nil),    // 1: anovel.genai.v1.Generation
}
var file_anovel_genai_v1_generation_proto_depIdxs = []int32{
	0, // 0: anovel.genai.v1.Generation.status:type_name -> anovel.genai.v1.GenerationStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anovel_genai_v1_generation_proto_init() }
func file_anovel_genai_v1_generation_proto_init() {
	if File_anovel_genai_v1_generation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_genai_v1_generation_proto_rawDesc), len(file_anovel_genai_v1_generation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anovel_genai_v1_generation_proto_goTypes,
		DependencyIndexes: file_anovel_genai_v1_generation_proto_depIdxs,
		EnumInfos:         file_anovel_genai_v1_generation_proto_enumTypes,
		MessageInfos:      file_anovel_genai_v1_generation_proto_msgTypes,
	}.Build()
	File_anovel_genai_v1_generation_proto = out.File
	file_anovel_genai_v1_generation_proto_goTypes = nil
	file_anovel_genai_v1_generation_proto_depIdxs = nil
}
