// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: anovel/genai/v1/usage_query.proto

package genaiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UsageQueryRequest scopes the read to one owner and one window.
type UsageQueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OwnerID whose consumption to report, formatted as a UUID.
	OwnerId string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	// From is inclusive, formatted as RFC 3339. Required: this record is never purged, so an
	// unbounded scan grows without limit and a caller has no way to know it asked for one.
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// To is exclusive, formatted as RFC 3339, so adjacent windows neither overlap nor skip a row.
	To string `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	// Purpose narrows the result to one attribution label. Empty means no filter.
	Purpose string `protobuf:"bytes,4,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// Model narrows the result to one model. Empty means no filter.
	Model         string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageQueryRequest) Reset() {
	*x = UsageQueryRequest{}
	mi := &file_anovel_genai_v1_usage_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageQueryRequest) ProtoMessage() {}

func (x *UsageQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v1_usage_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageQueryRequest.ProtoReflect.Descriptor instead.
func (*UsageQueryRequest) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v1_usage_query_proto_rawDescGZIP(), []int{0}
}

func (x *UsageQueryRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *UsageQueryRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *UsageQueryRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *UsageQueryRequest) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *UsageQueryRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

// UsageGroup is what one purpose and model consumed over the window.
type UsageGroup struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Purpose string                 `protobuf:"bytes,1,opt,name=purpose,proto3" json:"purpose,omitempty"`
	// Model that actually billed, as the provider reported it — not the alias a request asked for.
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Totals include their detail counts, as the provider counts them.
	InputTokens       int64 `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	CachedInputTokens int64 `protobuf:"varint,4,opt,name=cached_input_tokens,json=cachedInputTokens,proto3" json:"cached_input_tokens,omitempty"`
	OutputTokens      int64 `protobuf:"varint,5,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ReasoningTokens   int64 `protobuf:"varint,6,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	// Attempts counts the runs behind the group. A retried generation contributes more than one,
	// because it consumed more than once.
	Attempts      int64 `protobuf:"varint,7,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageGroup) Reset() {
	*x = UsageGroup{}
	mi := &file_anovel_genai_v1_usage_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageGroup) ProtoMessage() {}

func (x *UsageGroup) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v1_usage_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageGroup.ProtoReflect.Descriptor instead.
func (*UsageGroup) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v1_usage_query_proto_rawDescGZIP(), []int{1}
}

func (x *UsageGroup) GetPurpose() string {
	if x != nil {
		return x.Purpose
	}
	return ""
}

func (x *UsageGroup) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UsageGroup) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageGroup) GetCachedInputTokens() int64 {
	if x != nil {
		return x.CachedInputTokens
	}
	return 0
}

func (x *UsageGroup) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageGroup) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *UsageGroup) GetAttempts() int64 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

// UsageTotal is consumption with the dimensions collapsed.
type UsageTotal struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InputTokens       int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	CachedInputTokens int64                  `protobuf:"varint,2,opt,name=cached_input_tokens,json=cachedInputTokens,proto3" json:"cached_input_tokens,omitempty"`
	OutputTokens      int64                  `protobuf:"varint,3,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	ReasoningTokens   int64                  `protobuf:"varint,4,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	Attempts          int64                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UsageTotal) Reset() {
	*x = UsageTotal{}
	mi := &file_anovel_genai_v1_usage_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageTotal) ProtoMessage() {}

func (x *UsageTotal) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v1_usage_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageTotal.ProtoReflect.Descriptor instead.
func (*UsageTotal) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v1_usage_query_proto_rawDescGZIP(), []int{2}
}

func (x *UsageTotal) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageTotal) GetCachedInputTokens() int64 {
	if x != nil {
		return x.CachedInputTokens
	}
	return 0
}

func (x *UsageTotal) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageTotal) GetReasoningTokens() int64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *UsageTotal) GetAttempts() int64 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

// UsageQueryResponse reports consumption grouped by purpose and model, and summed.
type UsageQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Groups is one entry per purpose and model, ordered by both. A pricing layer needs these,
	// because a rate applies per model.
	Groups []*UsageGroup `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	// Total is every group summed. A quota layer wants only this.
	Total         *UsageTotal `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageQueryResponse) Reset() {
	*x = UsageQueryResponse{}
	mi := &file_anovel_genai_v1_usage_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageQueryResponse) ProtoMessage() {}

func (x *UsageQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anovel_genai_v1_usage_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageQueryResponse.ProtoReflect.Descriptor instead.
func (*UsageQueryResponse) Descriptor() ([]byte, []int) {
	return file_anovel_genai_v1_usage_query_proto_rawDescGZIP(), []int{3}
}

func (x *UsageQueryResponse) GetGroups() []*UsageGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UsageQueryResponse) GetTotal() *UsageTotal {
	if x != nil {
		return x.Total
	}
	return nil
}

var File_anovel_genai_v1_usage_query_proto protoreflect.FileDescriptor

const file_anovel_genai_v1_usage_query_proto_rawDesc = "" +
	"\n" +
	"!anovel/genai/v1/usage_query.proto\x12\x0fanovel.genai.v1\"\x82\x01\n" +
	"\x11UsageQueryRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\apurpose\x18\x04 \x01(\tR\apurpose\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"\xfb\x01\n" +
	"\n" +
	"UsageGroup\x12\x18\n" +
	"\apurpose\x18\x01 \x01(\tR\apurpose\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x03R\vinputTokens\x12.\n" +
	"\x13cached_input_tokens\x18\x04 \x01(\x03R\x11cachedInputTokens\x12#\n" +
	"\routput_tokens\x18\x05 \x01(\x03R\foutputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x06 \x01(\x03R\x0freasoningTokens\x12\x1a\n" +
	"\battempts\x18\a \x01(\x03R\battempts\"\xcb\x01\n" +
	"\n" +
	"UsageTotal\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12.\n" +
	"\x13cached_input_tokens\x18\x02 \x01(\x03R\x11cachedInputTokens\x12#\n" +
	"\routput_tokens\x18\x03 \x01(\x03R\foutputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x04 \x01(\x03R\x0freasoningTokens\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x03R\battempts\"|\n" +
	"\x12UsageQueryResponse\x123\n" +
	"\x06groups\x18\x01 \x03(\v2\x1b.anovel.genai.v1.UsageGroupR\x06groups\x121\n" +
	"\x05total\x18\x02 \x01(\v2\x1b.anovel.genai.v1.UsageTotalR\x05total2j\n" +
	"\x11UsageQueryService\x12U\n" +
	"\n" +
	"UsageQuery\x12\".anovel.genai.v1.UsageQueryRequest\x1a#.anovel.genai.v1.UsageQueryResponseB\xd9\x01\n" +
	"\x13com.anovel.genai.v1B\x0fUsageQueryProtoP\x01ZSgithub.com/a-novel/service-genai/internal/handlers/protogen/anovel/genai/v1;genaiv1\xa2\x02\x03AGX\xaa\x02\x0fAnovel.Genai.V1\xca\x02\x0fAnovel\\Genai\\V1\xe2\x02\x1bAnovel\\Genai\\V1\\GPBMetadata\xea\x02\x11Anovel::Genai::V1b\x06proto3"

var (
	file_anovel_genai_v1_usage_query_proto_rawDescOnce sync.Once
	file_anovel_genai_v1_usage_query_proto_rawDescData []byte
)

func file_anovel_genai_v1_usage_query_proto_rawDescGZIP() []byte {
	file_anovel_genai_v1_usage_query_proto_rawDescOnce.Do(func() {
		file_anovel_genai_v1_usage_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anovel_genai_v1_usage_query_proto_rawDesc), len(file_anovel_genai_v1_usage_query_proto_rawDesc)))
	})
	return file_anovel_genai_v1_usage_query_proto_rawDescData
}

var file_anovel_genai_v1_usage_query_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_anovel_genai_v1_usage_query_proto_goTypes = []any{
	(*UsageQueryRequest)(nil),  // 0: anovel.genai.v1.UsageQueryRequest
	(*UsageGroup)(nil),         // 1: anovel.genai.v1.UsageGroup
	(*UsageTotal)(nil),         // 2: anovel.genai.v1.UsageTotal
	(*UsageQueryResponse)(nil), // 3: anovel.genai.v1.UsageQueryResponse
}
var file_anovel_genai_v1_usage_query_proto_depIdxs = []int32{
	1, // 0: anovel.genai.v1.UsageQueryResponse.groups:type_name -> anovel.genai.v1.UsageGroup
	2, // 1: anovel.genai.v1.UsageQueryResponse.total:type_name -> anovel.genai.v1.UsageTotal
	0, // 2: anovel.genai.v1.UsageQueryService.UsageQuery:input_type -> anovel.genai.v1.UsageQueryRequest
	3, // 3: anovel.genai.v1.UsageQueryService.UsageQuery:output_type -> anovel.genai.v1.UsageQueryResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_anovel_genai_v1_usage_query_proto_init() }
func file_anovel_genai_v1_usage_query_proto_init() {
	if File_anovel_genai_v1_usage_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anovel_genai_v1_usage_query_proto_rawDesc), len(file_anovel_genai_v1_usage_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anovel_genai_v1_usage_query_proto_goTypes,
		DependencyIndexes: file_anovel_genai_v1_usage_query_proto_depIdxs,
		MessageInfos:      file_anovel_genai_v1_usage_query_proto_msgTypes,
	}.Build()
	File_anovel_genai_v1_usage_query_proto = out.File
	file_anovel_genai_v1_usage_query_proto_goTypes = nil
	file_anovel_genai_v1_usage_query_proto_depIdxs = nil
}
