// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: generation_watch.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerationWatchRequest identifies the generation to watch and the owner it must belong to.
type GenerationWatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the generation to watch, formatted as a UUID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// OwnerID scopes the watch, formatted as a UUID. Another owner's generation reports not-found.
	OwnerId       string `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationWatchRequest) Reset() {
	*x = GenerationWatchRequest{}
	mi := &file_generation_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationWatchRequest) ProtoMessage() {}

func (x *GenerationWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generation_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationWatchRequest.ProtoReflect.Descriptor instead.
func (*GenerationWatchRequest) Descriptor() ([]byte, []int) {
	return file_generation_watch_proto_rawDescGZIP(), []int{0}
}

func (x *GenerationWatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GenerationWatchRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

// GenerationWatchResponse carries one snapshot of the watched generation. One is sent on subscribe
// and one on each change until it is terminal.
type GenerationWatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    *Generation            `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationWatchResponse) Reset() {
	*x = GenerationWatchResponse{}
	mi := &file_generation_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationWatchResponse) ProtoMessage() {}

func (x *GenerationWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generation_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationWatchResponse.ProtoReflect.Descriptor instead.
func (*GenerationWatchResponse) Descriptor() ([]byte, []int) {
	return file_generation_watch_proto_rawDescGZIP(), []int{1}
}

func (x *GenerationWatchResponse) GetGeneration() *Generation {
	if x != nil {
		return x.Generation
	}
	return nil
}

var File_generation_watch_proto protoreflect.FileDescriptor

const file_generation_watch_proto_rawDesc = "" +
	"\n" +
	"\x16generation_watch.proto\x1a\x10generation.proto\"C\n" +
	"\x16GenerationWatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\"F\n" +
	"\x17GenerationWatchResponse\x12+\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\v.GenerationR\n" +
	"generation2`\n" +
	"\x16GenerationWatchService\x12F\n" +
	"\x0fGenerationWatch\x12\x17.GenerationWatchRequest\x1a\x18.GenerationWatchResponse0\x01B^B\x14GenerationWatchProtoP\x01ZDgithub.com/a-novel/service-genai/internal/handlers/protogen;protogenb\x06proto3"

var (
	file_generation_watch_proto_rawDescOnce sync.Once
	file_generation_watch_proto_rawDescData []byte
)

func file_generation_watch_proto_rawDescGZIP() []byte {
	file_generation_watch_proto_rawDescOnce.Do(func() {
		file_generation_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generation_watch_proto_rawDesc), len(file_generation_watch_proto_rawDesc)))
	})
	return file_generation_watch_proto_rawDescData
}

var file_generation_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_generation_watch_proto_goTypes = []any{
	(*GenerationWatchRequest)(nil),  // 0: GenerationWatchRequest
	(*GenerationWatchResponse)(nil), // 1: GenerationWatchResponse
	(*Generation)(nil),              // 2: Generation
}
var file_generation_watch_proto_depIdxs = []int32{
	2, // 0: GenerationWatchResponse.generation:type_name -> Generation
	0, // 1: GenerationWatchService.GenerationWatch:input_type -> GenerationWatchRequest
	1, // 2: GenerationWatchService.GenerationWatch:output_type -> GenerationWatchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_generation_watch_proto_init() }
func file_generation_watch_proto_init() {
	if File_generation_watch_proto != nil {
		return
	}
	file_generation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generation_watch_proto_rawDesc), len(file_generation_watch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generation_watch_proto_goTypes,
		DependencyIndexes: file_generation_watch_proto_depIdxs,
		MessageInfos:      file_generation_watch_proto_msgTypes,
	}.Build()
	File_generation_watch_proto = out.File
	file_generation_watch_proto_goTypes = nil
	file_generation_watch_proto_depIdxs = nil
}
