// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: generation_get.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenerationGetService_GenerationGet_FullMethodName = "/GenerationGetService/GenerationGet"
)

// GenerationGetServiceClient is the client API for GenerationGetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GenerationGetService reads one of an owner's generations. A generation owned by anyone else
// reports not-found, so the read cannot be used to learn whether an id exists.
type GenerationGetServiceClient interface {
	GenerationGet(ctx context.Context, in *GenerationGetRequest, opts ...grpc.CallOption) (*GenerationGetResponse, error)
}

type generationGetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGenerationGetServiceClient(cc grpc.ClientConnInterface) GenerationGetServiceClient {
	return &generationGetServiceClient{cc}
}

func (c *generationGetServiceClient) GenerationGet(ctx context.Context, in *GenerationGetRequest, opts ...grpc.CallOption) (*GenerationGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerationGetResponse)
	err := c.cc.Invoke(ctx, GenerationGetService_GenerationGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenerationGetServiceServer is the server API for GenerationGetService service.
// All implementations must embed UnimplementedGenerationGetServiceServer
// for forward compatibility.
//
// GenerationGetService reads one of an owner's generations. A generation owned by anyone else
// reports not-found, so the read cannot be used to learn whether an id exists.
type GenerationGetServiceServer interface {
	GenerationGet(context.Context, *GenerationGetRequest) (*GenerationGetResponse, error)
	mustEmbedUnimplementedGenerationGetServiceServer()
}

// UnimplementedGenerationGetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenerationGetServiceServer struct{}

func (UnimplementedGenerationGetServiceServer) GenerationGet(context.Context, *GenerationGetRequest) (*GenerationGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerationGet not implemented")
}
func (UnimplementedGenerationGetServiceServer) mustEmbedUnimplementedGenerationGetServiceServer() {}
func (UnimplementedGenerationGetServiceServer) testEmbeddedByValue()                              {}

// UnsafeGenerationGetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenerationGetServiceServer will
// result in compilation errors.
type UnsafeGenerationGetServiceServer interface {
	mustEmbedUnimplementedGenerationGetServiceServer()
}

func RegisterGenerationGetServiceServer(s grpc.ServiceRegistrar, srv GenerationGetServiceServer) {
	// If the following call panics, it indicates UnimplementedGenerationGetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenerationGetService_ServiceDesc, srv)
}

func _GenerationGetService_GenerationGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerationGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenerationGetServiceServer).GenerationGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenerationGetService_GenerationGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenerationGetServiceServer).GenerationGet(ctx, req.(*GenerationGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GenerationGetService_ServiceDesc is the grpc.ServiceDesc for GenerationGetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenerationGetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GenerationGetService",
	HandlerType: (*GenerationGetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerationGet",
			Handler:    _GenerationGetService_GenerationGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generation_get.proto",
}
