// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: usage_query.proto

package protogen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsageQueryService_UsageQuery_FullMethodName = "/UsageQueryService/UsageQuery"
)

// UsageQueryServiceClient is the client API for UsageQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UsageQueryService reports what an owner consumed over a window.
//
// It returns tokens, never money. What a token costs is a downstream decision, which is why the
// model that actually billed is carried on every group.
type UsageQueryServiceClient interface {
	UsageQuery(ctx context.Context, in *UsageQueryRequest, opts ...grpc.CallOption) (*UsageQueryResponse, error)
}

type usageQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsageQueryServiceClient(cc grpc.ClientConnInterface) UsageQueryServiceClient {
	return &usageQueryServiceClient{cc}
}

func (c *usageQueryServiceClient) UsageQuery(ctx context.Context, in *UsageQueryRequest, opts ...grpc.CallOption) (*UsageQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageQueryResponse)
	err := c.cc.Invoke(ctx, UsageQueryService_UsageQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsageQueryServiceServer is the server API for UsageQueryService service.
// All implementations must embed UnimplementedUsageQueryServiceServer
// for forward compatibility.
//
// UsageQueryService reports what an owner consumed over a window.
//
// It returns tokens, never money. What a token costs is a downstream decision, which is why the
// model that actually billed is carried on every group.
type UsageQueryServiceServer interface {
	UsageQuery(context.Context, *UsageQueryRequest) (*UsageQueryResponse, error)
	mustEmbedUnimplementedUsageQueryServiceServer()
}

// UnimplementedUsageQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsageQueryServiceServer struct{}

func (UnimplementedUsageQueryServiceServer) UsageQuery(context.Context, *UsageQueryRequest) (*UsageQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UsageQuery not implemented")
}
func (UnimplementedUsageQueryServiceServer) mustEmbedUnimplementedUsageQueryServiceServer() {}
func (UnimplementedUsageQueryServiceServer) testEmbeddedByValue()                           {}

// UnsafeUsageQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsageQueryServiceServer will
// result in compilation errors.
type UnsafeUsageQueryServiceServer interface {
	mustEmbedUnimplementedUsageQueryServiceServer()
}

func RegisterUsageQueryServiceServer(s grpc.ServiceRegistrar, srv UsageQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedUsageQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsageQueryService_ServiceDesc, srv)
}

func _UsageQueryService_UsageQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsageQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsageQueryServiceServer).UsageQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsageQueryService_UsageQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsageQueryServiceServer).UsageQuery(ctx, req.(*UsageQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsageQueryService_ServiceDesc is the grpc.ServiceDesc for UsageQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsageQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UsageQueryService",
	HandlerType: (*UsageQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UsageQuery",
			Handler:    _UsageQueryService_UsageQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usage_query.proto",
}
