// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package libmocks

import (
	"context"

	"github.com/a-novel/service-genai/internal/lib"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockProvider
func (_mock *MockProvider) Cancel(ctx context.Context, id string) (*lib.ProviderCall, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 *lib.ProviderCall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*lib.ProviderCall, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *lib.ProviderCall); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ProviderCall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockProvider_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProvider_Expecter) Cancel(ctx any, id any) *MockProvider_Cancel_Call {
	return &MockProvider_Cancel_Call{Call: _e.mock.On("Cancel", ctx, id)}
}

func (_c *MockProvider_Cancel_Call) Run(run func(ctx context.Context, id string)) *MockProvider_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Cancel_Call) Return(providerCall *lib.ProviderCall, err error) *MockProvider_Cancel_Call {
	_c.Call.Return(providerCall, err)
	return _c
}

func (_c *MockProvider_Cancel_Call) RunAndReturn(run func(ctx context.Context, id string) (*lib.ProviderCall, error)) *MockProvider_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockProvider
func (_mock *MockProvider) Get(ctx context.Context, id string) (*lib.ProviderCall, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *lib.ProviderCall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*lib.ProviderCall, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *lib.ProviderCall); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ProviderCall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProvider_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProvider_Expecter) Get(ctx any, id any) *MockProvider_Get_Call {
	return &MockProvider_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockProvider_Get_Call) Run(run func(ctx context.Context, id string)) *MockProvider_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Get_Call) Return(providerCall *lib.ProviderCall, err error) *MockProvider_Get_Call {
	_c.Call.Return(providerCall, err)
	return _c
}

func (_c *MockProvider_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (*lib.ProviderCall, error)) *MockProvider_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProvider
func (_mock *MockProvider) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Name() *MockProvider_Name_Call {
	return &MockProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProvider_Name_Call) Run(run func()) *MockProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Name_Call) Return(s string) *MockProvider_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProvider_Name_Call) RunAndReturn(run func() string) *MockProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockProvider
func (_mock *MockProvider) Start(ctx context.Context, request *lib.ProviderStartRequest) (*lib.ProviderCall, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 *lib.ProviderCall
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lib.ProviderStartRequest) (*lib.ProviderCall, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lib.ProviderStartRequest) *lib.ProviderCall); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lib.ProviderCall)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lib.ProviderStartRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProvider_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockProvider_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - request *lib.ProviderStartRequest
func (_e *MockProvider_Expecter) Start(ctx any, request any) *MockProvider_Start_Call {
	return &MockProvider_Start_Call{Call: _e.mock.On("Start", ctx, request)}
}

func (_c *MockProvider_Start_Call) Run(run func(ctx context.Context, request *lib.ProviderStartRequest)) *MockProvider_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lib.ProviderStartRequest
		if args[1] != nil {
			arg1 = args[1].(*lib.ProviderStartRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_Start_Call) Return(providerCall *lib.ProviderCall, err error) *MockProvider_Start_Call {
	_c.Call.Return(providerCall, err)
	return _c
}

func (_c *MockProvider_Start_Call) RunAndReturn(run func(ctx context.Context, request *lib.ProviderStartRequest) (*lib.ProviderCall, error)) *MockProvider_Start_Call {
	_c.Call.Return(run)
	return _c
}
