// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/a-novel/service-genai/internal/core"
	"github.com/a-novel/service-genai/internal/dao"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGrpcGenerationCancelService creates a new instance of MockGrpcGenerationCancelService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrpcGenerationCancelService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrpcGenerationCancelService {
	mock := &MockGrpcGenerationCancelService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrpcGenerationCancelService is an autogenerated mock type for the GrpcGenerationCancelService type
type MockGrpcGenerationCancelService struct {
	mock.Mock
}

type MockGrpcGenerationCancelService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrpcGenerationCancelService) EXPECT() *MockGrpcGenerationCancelService_Expecter {
	return &MockGrpcGenerationCancelService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGrpcGenerationCancelService
func (_mock *MockGrpcGenerationCancelService) Exec(ctx context.Context, request *core.GenerationCancelRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCancelRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationCancelRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationCancelRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpcGenerationCancelService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGrpcGenerationCancelService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationCancelRequest
func (_e *MockGrpcGenerationCancelService_Expecter) Exec(ctx any, request any) *MockGrpcGenerationCancelService_Exec_Call {
	return &MockGrpcGenerationCancelService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGrpcGenerationCancelService_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationCancelRequest)) *MockGrpcGenerationCancelService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationCancelRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationCancelRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpcGenerationCancelService_Exec_Call) Return(generation *dao.Generation, err error) *MockGrpcGenerationCancelService_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGrpcGenerationCancelService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationCancelRequest) (*dao.Generation, error)) *MockGrpcGenerationCancelService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGrpcGenerationGetService creates a new instance of MockGrpcGenerationGetService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrpcGenerationGetService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrpcGenerationGetService {
	mock := &MockGrpcGenerationGetService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrpcGenerationGetService is an autogenerated mock type for the GrpcGenerationGetService type
type MockGrpcGenerationGetService struct {
	mock.Mock
}

type MockGrpcGenerationGetService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrpcGenerationGetService) EXPECT() *MockGrpcGenerationGetService_Expecter {
	return &MockGrpcGenerationGetService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGrpcGenerationGetService
func (_mock *MockGrpcGenerationGetService) Exec(ctx context.Context, request *core.GenerationGetRequest) (*dao.Generation, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *dao.Generation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationGetRequest) (*dao.Generation, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationGetRequest) *dao.Generation); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dao.Generation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationGetRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpcGenerationGetService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGrpcGenerationGetService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationGetRequest
func (_e *MockGrpcGenerationGetService_Expecter) Exec(ctx any, request any) *MockGrpcGenerationGetService_Exec_Call {
	return &MockGrpcGenerationGetService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGrpcGenerationGetService_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationGetRequest)) *MockGrpcGenerationGetService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationGetRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationGetRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpcGenerationGetService_Exec_Call) Return(generation *dao.Generation, err error) *MockGrpcGenerationGetService_Exec_Call {
	_c.Call.Return(generation, err)
	return _c
}

func (_c *MockGrpcGenerationGetService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationGetRequest) (*dao.Generation, error)) *MockGrpcGenerationGetService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGrpcGenerationSubmitService creates a new instance of MockGrpcGenerationSubmitService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrpcGenerationSubmitService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrpcGenerationSubmitService {
	mock := &MockGrpcGenerationSubmitService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrpcGenerationSubmitService is an autogenerated mock type for the GrpcGenerationSubmitService type
type MockGrpcGenerationSubmitService struct {
	mock.Mock
}

type MockGrpcGenerationSubmitService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrpcGenerationSubmitService) EXPECT() *MockGrpcGenerationSubmitService_Expecter {
	return &MockGrpcGenerationSubmitService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGrpcGenerationSubmitService
func (_mock *MockGrpcGenerationSubmitService) Exec(ctx context.Context, request *core.GenerationSubmitRequest) (*core.GenerationSubmitResult, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.GenerationSubmitResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationSubmitRequest) (*core.GenerationSubmitResult, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *core.GenerationSubmitRequest) *core.GenerationSubmitResult); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.GenerationSubmitResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *core.GenerationSubmitRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpcGenerationSubmitService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGrpcGenerationSubmitService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.GenerationSubmitRequest
func (_e *MockGrpcGenerationSubmitService_Expecter) Exec(ctx any, request any) *MockGrpcGenerationSubmitService_Exec_Call {
	return &MockGrpcGenerationSubmitService_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockGrpcGenerationSubmitService_Exec_Call) Run(run func(ctx context.Context, request *core.GenerationSubmitRequest)) *MockGrpcGenerationSubmitService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *core.GenerationSubmitRequest
		if args[1] != nil {
			arg1 = args[1].(*core.GenerationSubmitRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGrpcGenerationSubmitService_Exec_Call) Return(generationSubmitResult *core.GenerationSubmitResult, err error) *MockGrpcGenerationSubmitService_Exec_Call {
	_c.Call.Return(generationSubmitResult, err)
	return _c
}

func (_c *MockGrpcGenerationSubmitService_Exec_Call) RunAndReturn(run func(ctx context.Context, request *core.GenerationSubmitRequest) (*core.GenerationSubmitResult, error)) *MockGrpcGenerationSubmitService_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGrpcStatusQueueDepthService creates a new instance of MockGrpcStatusQueueDepthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGrpcStatusQueueDepthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGrpcStatusQueueDepthService {
	mock := &MockGrpcStatusQueueDepthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGrpcStatusQueueDepthService is an autogenerated mock type for the GrpcStatusQueueDepthService type
type MockGrpcStatusQueueDepthService struct {
	mock.Mock
}

type MockGrpcStatusQueueDepthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGrpcStatusQueueDepthService) EXPECT() *MockGrpcStatusQueueDepthService_Expecter {
	return &MockGrpcStatusQueueDepthService_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockGrpcStatusQueueDepthService
func (_mock *MockGrpcStatusQueueDepthService) Exec(ctx context.Context) (*core.QueueDepthResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *core.QueueDepthResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*core.QueueDepthResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *core.QueueDepthResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.QueueDepthResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGrpcStatusQueueDepthService_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGrpcStatusQueueDepthService_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockGrpcStatusQueueDepthService_Expecter) Exec(ctx any) *MockGrpcStatusQueueDepthService_Exec_Call {
	return &MockGrpcStatusQueueDepthService_Exec_Call{Call: _e.mock.On("Exec", ctx)}
}

func (_c *MockGrpcStatusQueueDepthService_Exec_Call) Run(run func(ctx context.Context)) *MockGrpcStatusQueueDepthService_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGrpcStatusQueueDepthService_Exec_Call) Return(queueDepthResult *core.QueueDepthResult, err error) *MockGrpcStatusQueueDepthService_Exec_Call {
	_c.Call.Return(queueDepthResult, err)
	return _c
}

func (_c *MockGrpcStatusQueueDepthService_Exec_Call) RunAndReturn(run func(ctx context.Context) (*core.QueueDepthResult, error)) *MockGrpcStatusQueueDepthService_Exec_Call {
	_c.Call.Return(run)
	return _c
}
